### ISSUE TITLE
Question: Typescript definition for Navigation-React?

### ISSUE THREAD

**Issue by jmathew** [grahammendick/navigation#103]
Is there a pre-existing definition file for the Navigation-React lib?

**Comment by grahammendick** [comment]
Thanks for the great question. There's a [Typescript definition for Navigation](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/navigation/navigation.d.ts) but not for Navigation React.

You see, Navigation has most of the functionality. Navigation React only has a few React Components for the Hyperlinks. But if you think it would be helpful to have a definition file for the Components let me know.

**Comment by jmathew** [comment]
Yes, I've taken a closer look at the code. And you're not kidding! 

Really the only thing that would be nice is an interface for the props. It looks like all the type checking for props on the components is done by LinkUtility. I think an interface definition on top of that would be helpful for compile time checking and completion.

**Comment by grahammendick** [comment]
I agree. There's definitely merit in a props interface. Thanks for the suggestion. 

If you're interested on working on it, let me know. Don't worry if you're not because I'm more than happy to do it.

**Comment by jmathew** [comment]
Thanks, I'll leave it in your hands. I don't think I know the code well enough to write comments for the definition I'd be writing, which I take to be a pretty good sign I shouldn't be writing it.

**Comment by grahammendick** [comment]
No worries. Thanks again for the suggestion. I'll leave this open until I've added it.

**Comment by grahammendick** [comment]
I've created the [Navigation React typings](https://github.com/grahammendick/navigation/blob/master/NavigationReact/test/node_modules/%40types/navigation-react.d.ts). @jmathew Could you give them a once over and check you're happy, please?

All the prop types inherit from `HTMLProps<HTMLAnchorElement>` because the three Link components accept all the props that an anchor element accepts, e.g., `target`.
```jsx
<NavigationLink stateKey="people" target="_blank" />
```
Be warned that the `HTMLAnchorElement` accepts any prop key as valid because it supports `data-*` and `aria-*` attributes. So, TypeScript won't complain if you do this:
```jsx
<NavigationLink stateKey="people" x="y" />
```
If you're happy, I'll create a pull request on [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) and will keep this open until that's merge in.

**Comment by jmathew** [comment]
Looks good to me. Thanks for the quick turnaround.

**Comment by grahammendick** [comment]
The [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13267) has been merged into Definitely Typed. @jmathew  Thanks again for raising the issue
