### ISSUE TITLE
Navigation bar options

### ISSUE THREAD

**Issue by jacobp100** [grahammendick/navigation#235]
I'd like to disable the native navigation bar for some routes. How do you feel about an API similar to `{RightLeft}BarIOS` to set the navgiation bar props? Other than hiding, there'll be use-cases like `tintColor`, `barStyle` etc.

I can try and submit a PR if you're happy with that direction and I test it for my use-cases

**Comment by grahammendick** [comment]
Hey Jacob, thanks for getting in touch and for the great idea. Just to make sure I understand correctly, please give me an example of a screen where you’d want to hide the navigation bar.

Technically, the `{RightLeft}BarIOS` components didn’t have to be part of this repository because they have no Navigation router dependencies. But since the router owns the IOS navigation bar, I think the router should provide the components to manipulate it.

I’d really appreciate it if you submit a `NavigationBarIOS` component PR. Like you say, there are other use cases like `tintColor` but I’m happy that your PR only focuses on your 'hiding' use-case.

**Comment by jacobp100** [comment]
Yeah you’re right, I can just roll my own native view for this.

I’ll do that for my current project, play around with it, see what works well, and send a PR.

What might make sense long term is docs on how to do this, then for the more unique cases, people just write native code.

For completeness, the hiding use-case is for if you want to roll your own navigation bar, or you want a YouTube player like page, that just doesn’t have a navigation bar

**Comment by grahammendick** [comment]
Sounds good. I look forward to your PR. If you've any questions or suggestions just let me know

**Comment by jacobp100** [comment]
Okay, I don't think we can do the view approach, it's just too flaky. It'll be incorrectly hidden, or the animation will just be off.

For now, I've done a work around in app delegate,

```objc
- (void)navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated
{
  if ([viewController isKindOfClass:[NVSceneController class]] &&
      [(NVSceneController *) viewController crumb] == 0) {
    [navigationController setNavigationBarHidden:YES animated:animated];
  } else {
    [navigationController setNavigationBarHidden:NO animated:animated];
  }
}
```

This is super smooth, like other native apps.

I'm not sure what's the nicest API to expose this. I think at minimum, `NVSceneController` should contain the key of the scene, so the user can configure it manually.

We could also be like `NavigatorIOS`, and have `navigationBarHidden`, `tintColor` in the scene config (and also `NVSceneController`).

Or maybe this is beyond the scope. I'm able to handle my use case, so feel free to close if you think it's a bridge too far!

**Comment by grahammendick** [comment]
I’m glad you’ve found a workaround. There's nowt worse than being stuck!

> it's just too flaky. It'll be incorrectly hidden

Can you clarify what you mean? Is the problem that the navigation bar isn’t hidden until the view content loads which currently happens asynchronously? I tried it in my [zoom sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/zoom) and didn’t notice any delay but that’s probably because the views are small and load fast?

I’d like to understand the possible use-cases for hiding the navigation bar a bit better. Are there use-cases where you’d want to start with the navigation bar shown and then hide it based on a user interaction (without changing scene)?

**Comment by jacobp100** [comment]
In your example, are you talking about the bar buttons?

The biggest problem I had was doing the peek gesture and cancelling would leave the navigation bar in the wrong state. But other than that, the animation was wrong too: if you navigate from a page without a navigation bar to a page with, it slides in from the right and not the top.

My use case is purely one of the scenes doesn't have a navigation bar. However, you might hide the navigation bar on scroll, and you'd also want to customise the animations on that. I think `NavigatorIOS` never supported changing the props once the scene mounted, but I definitely remember some tickets asking for it.

**Comment by grahammendick** [comment]
Just to see test out how it behaved I hid the navigation bar inside the [RightBarIOS](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/src/ios/NVRightBarView.m). When I hid the bar I couldn’t do the peek gesture. How do you get the swipe back to work when the bar is hidden?

If you were building an iOS app **without React Native** and wanted to hide the navigation bar, where would you put the code?

**Comment by jacobp100** [comment]
I was going from no bar to having a bar, so didn’t really hit that case (except when the bar got hidden incorrectly.)

I did some research on how to do it normally in iOS, and I think the solution I posted above is the Apple way to do it. It’s a method on UINavigationControllerDelegate.

**Comment by grahammendick** [comment]
Aaah, you went from no bar to bar, that makes sense now thanks. Also, thanks for pointing me at `NavigatorIOS`. It’s handy to see their approach.

I guess we could treat it the same way that I handle the title for iOS. We can add an optional `navigationBar` `hidden` property to a `State`. Then we pass the value to the [NavigationModule](https://github.com/grahammendick/navigation/blob/58ab6b740e6def9a4e71bb8ad27b44df28a11be4/NavigationReactNative/src/ios/NavigationModule.m#L22) during a navigation.
```js
var stateNavigator = new StateNavigator([
  {key: 'grid', title: 'Colors', navigationBar: {hidden: true}},
  {key: 'detail', title: 'Color', trackCrumbTrail: true},
]);
```
We can also follow the iOS title approach if you need to set the `hidden` property dynamically based on navigation data. In the twitter sample I set the [timeline scene title](https://github.com/grahammendick/navigation/blob/58ab6b740e6def9a4e71bb8ad27b44df28a11be4/NavigationReactNative/sample/twitter/App.js#L29) to the [person’s name](https://github.com/grahammendick/navigation/blob/58ab6b740e6def9a4e71bb8ad27b44df28a11be4/NavigationReactNative/sample/twitter/Tweets.js#L22)

We’d still probably need a `NavigationBarIOS` component so that the bar can be hidden and shown in response to a user interaction.

**Comment by grahammendick** [comment]
Hold on, can't we cover all use-cases with a `NavigationBarIOS` component if we add a `viewWillAppear` listener to make sure that the bar is reset on peek? But it still might have the problem of the bar sliding in from the right instead of the top.

**Comment by jacobp100** [comment]
I think I’m viewWillAppear we can’t get the view controller.

You’re right about needing a component to handle updating the nav bar config.

That kind of sucks if we might need the value of this synchronously for navigating.

But I wonder if it’s possible to add the child react side, reconcile the tree, but without navigating. Then we could collect the props before hand, and navigate after we know what they are.

**Comment by grahammendick** [comment]
I think we can handle all use-cases with a `NavigationBarIOS` component. This will mean that the navigation bar changes won't take effect until React Native loads the content. As long as the view loads fast enough this should be fine. I tried adding a 400ms to the React Component render and the bar still slides in from the right (although with a slight lag). When I upped the delay to 500ms then the bar slides in from the top. But if the delay’s this long then you have other problems because the screen stays blank so I don’t think we need to worry about this? Hopefully, when React Native Fabric lands they’ll load the view content synchronously.

Then we need a way to reset the navigation bar changes when the view will appear. One way I can think of doing this is to add a `UINavigationBar` property to the `NVSceneController`. When the `NavigationBarIOS` loads we can set this property. React Native lets us access the [view controller from the view](https://github.com/grahammendick/navigation/blob/58ab6b740e6def9a4e71bb8ad27b44df28a11be4/NavigationReactNative/src/ios/NVRightBarView.m#L9). Then the `NVSceneController` can reset the navigation bar from this property in its `viewWillAppear` method.

**Comment by jacobp100** [comment]
Did you have an example of the ObjC code you had for NavigationBarIOS?

**Comment by grahammendick** [comment]
This is a rough idea of what the ObC might look like. Let's keep it simple for now and assume there's only one `NavigationBarIOS` on each view controller

```objective-c
//NVNavigationBarView

- (void)setHidden:(BOOL)hidden
{
  //Set the value onto the iOS navigation bar
  [self.reactViewController.navigationController setNavigationBarHidden:hidden animated:YES];
}

- (void)didMoveToWindow
{
  [super didMoveToWindow];
  //Set the navigation bar view (self) onto the View Controller
  ((NVSceneController *) self.reactViewController).navigationBarView = self;
}

//NVSceneController

-(void)viewWillAppear:(BOOL)animated  
{  
  [super viewWillAppear:animated];
  // Reset the iOS navigation bar hidden property from the view (for peeking)
  If ([self.navigationBarView]) {
      [self.navigationController setNavigationBarHidden:self.navigationBarView.hidden animated:YES];        
  }
}
```

**Comment by jacobp100** [comment]
That does seem to work - at least by my testing!

One thought, we set the title of the views in `NavigationModule`. Does it make sense to set all navigation props there, move the title configuration to `NVSceneController`, or leave it?

**Comment by grahammendick** [comment]
That’s exciting! Great work!

Excellent question about the title. I thought the same thing but then I remembered why the title is different to the other props. The title is the only prop that appears on the next scene (as the back button text). The Navigation router supports [pushing multiple scenes at once](https://medium.com/@graham.mendick/navigation-patterns-in-react-native-b000c6f8d474). Say you start on scene A and then push scenes B and C at the same time. The back button text on scene C should display 'Title B' but scene B hasn’t rendered/appeared yet (it doesn’t render until you navigate back to it). So if we only set the title when scene B renders the back button on scene C won’t display correctly. 

But I do think there’s a lot of value in adding a title prop to the `NavigationBarIOS` component and to set the navigation bar title if the prop has a value. That way users can set the title declaratively and only have to resort to the non-declarative technique if they’re pushing multiple scenes  at once (which is a rare use-case).

**Comment by jacobp100** [comment]
Yeah, one thing I was wondering about is in `NavigationModule.m`, we have,

```objc
RCT_EXPORT_METHOD(render:(NSInteger)crumb tab:(NSInteger)tab titles:(NSArray *)titles appKey:(NSString *)appKey ...)
````

What I was thinking about is having

```objc
RCT_EXPORT_METHOD(render:(NSInteger)crumb tab:(NSInteger)tab navigaionBarPropertiesByKey:(NSDict<NSString *, NSDictionary<NSString *, id> *> *)properties appKey:(NSString *)appKey ...)
{
    ...
    for (NVSceneController *controller in [navigationController viewControllers]) {
        controller.navigaionBarProperties = [navigaionBarPropertiesByKey objectForKey:controller.key];
    }
    ...
}

RCT_EXPORT_METHOD(updateProperties:(NSString)forKey tab:(NSInteger)tab navigaionBarProperties:(NSDictionary<NSString *, id> *)properties)
{
    for (NVSceneController *controller in [navigationController viewControllers]) {
        if (controller.key == forKey) {
            controller.navigaionBarProperties = navigaionBarProperties;
        }
    }
}
```

And then there's some logic in NVSceneController in `setNavigationBarProperties` to set its title and update the navigation bar if it's visible.

So then you could statically define the config in your routing config if it won't change, or you could add a JS component to update stuff dynamically. Just some thoughts anyway, not tested, so it might not work in practice

**Comment by grahammendick** [comment]
Nice idea but we should avoid using the routing config if we can help it. We should only go that way if we have no choice like with titles when opening multiple screens at once.

**Comment by jacobp100** [comment]
Okay do you think about NVScenes having the key? For the niche cases where you want to roll your own navigation configurator?

**Comment by grahammendick** [comment]
Can you give me an example of when you'd need it?

**Comment by jacobp100** [comment]
So my [first fix](https://github.com/grahammendick/navigation/issues/235#issuecomment-488083049) was to just set a delegate on the UINavigationController, and configured the navigation bar from there. I did it based on the crumb, but that's a hack and only coincidentally correct for my use-case.

**Comment by grahammendick** [comment]
With the `NavigationBarIOS` component you don't need that fix anymore. Can you think of why you'd need the key now?

**Comment by jacobp100** [comment]
For cases where people want a heavily customised navigation bar. For example, some apps replace the title view with a segmented control. But that'd probably be too much for the NavigationBarIOS component to handle.

But also, if someone wanted update the navigation bar dynamically with heavily custom code, they'd need to know the key of the top route to make sure they're not editing the navigation bar for a different route.

**Comment by grahammendick** [comment]
Let's concentrate and the hidden use-case for now. But I'd be keen to investigate a more complex scenario in another PR if you're interested. We'd see if the NavigationBarIOS could support it

**Comment by jacobp100** [comment]
I'll try and get a PR out soon! Was just considering the advance cases. For my current project, I'm still iterating on the look, so I'm doing a lot of native navigation bar customisation - some of which would probably be generally useful in a navigation library, and some not so.

**Comment by grahammendick** [comment]
If you're interested we'll definitely pick this up in another PR

**Comment by grahammendick** [comment]
Darn it, you got me thinking about the next PR :)
I think we could implement a segmented title view using the `NavigationBarIOS` component. Something like this might work?
```jsx
<NavigationBarIOS>
  <TitleViewIOS>
    <Text>Hello</Text>
  </TitleViewIOS>
</NavigationBarIOS>
```

**Comment by jacobp100** [comment]
Segmented control as in this

![segmented control in navigation bar](https://i.stack.imgur.com/RvAyh.jpg)

**Comment by grahammendick** [comment]
Something like this?
```jsx
<NavigationBarIOS>
  <TitleViewIOS>
    <View>
      <Button title="All" style={{...}} />
      <Button title="Missed" style={{...}} />
      <Text>Recents</Text>
    </View>
  </TitleViewIOS>
</NavigationBarIOS>
```
React Native's [Modal component](https://facebook.github.io/react-native/docs/modal) does turn into a `UIViewController`. It's [pretty nifty](https://github.com/facebook/react-native/blob/master/React/Views/RCTModalHostView.m). I think we could use a similar technique for implementing a [`SearchBarIOS` component](https://developer.apple.com/documentation/uikit/view_controllers/displaying_searchable_content_by_using_a_search_controller?language=objc)

**Comment by grahammendick** [comment]
I’ve thought up a better way to reset the navigation bar when peeking and popping

## The Problem
Take the following example of a Stack with three screens.
```
A → B → C
```
There’s a `NavigationBarIOS` component on screen A that hides the navigation bar.
There’s no `NavigationBarIOS` component on B.
There’s a `NavigationBarIOS` component on screen C that shows the navigation bar.

## What does the navigation bar look like on screen B?
When going from A to B then screen B hides the navigation bar. 
When peeking or popping from C to B then screen B shows the navigation bar.

Because B doesn’t have a `NavigationBarIOS` component, its navigation bar retains the settings from the preceding screen. When pushing, it takes A’s settings and, when popping, it takes C’s settings.

# The Solution
Every screen, regardless of whether they contain a `NavigationBarIOS` component, should save and reset its navigation bar settings. 

In `viewWillDisappear` of `NVSceneController` save the navigation bar settings.
In `viewWillAppear` of `NVSceneController` restore the navigation bar settings.

As well as fixing the problem I think it makes the `NavigationBarIOS`  component easier to use. Add it to the first screen to set up some navigation bar defaults like the background color. Then only add it to subsequent screens to override these defaults.

Another advantage is that the `NVNavigationBarView` doesn’t have to know about the `UIViewController` (`NVSceneController`) anymore.

**Comment by jacobp100** [comment]
I like the bit about inheriting the navigation bar from the previous controller - I imagine that'll reduce a tonne of boilerplate code.

What's the mechanism for saving and restoring the navigation bar state? Just recording what properties were set on it, and then resetting them?

**Comment by grahammendick** [comment]
Yep, just store them as properties on the `NVSceneController`

**Comment by grahammendick** [comment]
@jacobp100 I've run into [a problem when building a Search Bar component for iOS](https://stackoverflow.com/questions/56392638/ios-search-bar-added-after-a-small-delay-doesn-t-appear-in-the-navigation-bar). Any idea how to get around it?

**Comment by jacobp100** [comment]
Is the reason it has the delay because the view creation in RN is async? If you could make that part sync, does that solve your issue?

**Comment by grahammendick** [comment]
I thought that making it sync would solve it but I've changed me mind. I create the `UISearchController` inside the `didMoveToWindow` of `UIView` and I think that's always async even if I the initial view creation is sync.

**Comment by grahammendick** [comment]
You should write a SearchBar component in your [Navigation Test](https://github.com/jacobp100/NavigatorTest). You might not have the problems I'm having because it's a single React root. 
You can copy the one [I'm working on](https://github.com/grahammendick/navigation/compare/search-bar) and see how it goes?

**Comment by jacobp100** [comment]
Yeah, I’m pretty sure I can add the search controller. My trick was that none of the components like SearchBar render to anything, they just set properties on the route they’re contained within. Then I can load a route with all properties already available

Hopefully I’ll get time to experiment with it more!

**Comment by grahammendick** [comment]
Let me know if you're still interested in doing this because I've got a different approach
