### ISSUE TITLE
Maturity of this project?

### ISSUE THREAD

**Issue by SudoPlz** [grahammendick/navigation#250]
Hey there, this is not a bug, it's more of a question.

How mature is this project?
Is any significant react-native app using it?

We're currently using `react-native-navigation` but find troublesome, where does this library stand in terms of maturity, features and performance in comparison to RNN?

I'd ask in SO but it would get closed in no time.

Thank you

**Comment by grahammendick** [comment]
Hey, thanks for asking.

The Navigation router isn't at all like React Native Navigation. I’ll explain how their features differ and, if you're still interested, then we can talk in more depth about maturity and performance and any other questions you have.

The Navigation router does almost all of its work in JavaScript. The Native side is only a thin wrapper around the JavaScript. Excluding the navigation bar, pretty much all the iOS Native code is contained in [`NVNavigationStackView`](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/src/ios/NVNavigationStackView.m). It's where the pushing and popping onto the `UINavigationController` happens. That's the exact opposite of RNN where there’s very little JavaScript in comparison to Native code.

Because most of the work happens on the JavaScript side, the Navigation router supports more navigation patterns than RNN. Like [jumping forward and backward through the Stack](https://medium.com/@graham.mendick/navigation-patterns-in-react-native-b000c6f8d474) and [replacing any scene in the Stack](https://medium.com/@graham.mendick/more-navigation-patterns-in-react-native-ea5892891cce). It also means the Navigation router runs just as well on the Web as on Android and iOS. I’ve written an example that shows a [single codebase that works on all three platforms](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/web).

The Navigation router will never support as many features as RNN because it has a much narrower scope. The Navigation router concentrates on navigation only so will never include a Modal or Drawer component. Also, the Navigation router only exposes the navigation features that are native to the platform. It doesn’t try to erase the platform differences. For example, the Navigation router only has shared element animation on Android because Android is the only platform that has a Native shared element API. Similarly, the search bar component won’t render anything on Android because iOS is the only one that has a Native search bar implementation.

**Comment by SudoPlz** [comment]
Thanks for the detailed answer! I appreciate it.

**Comment by grahammendick** [comment]
No problem. If you decided not to choose the Navigation router could you let me know why? It'll improve my understanding of the React Native landscape

**Comment by SudoPlz** [comment]
We haven't decided not to use it, it's just that we've spent countless hours integrating w/ v2 of RNN and despite it's flaws the amount of effort it would require to bake sth else into our app should be very well backed up before making a switch.
We don't know what unknowns your navigator may bring if we start integrating with it.

Sounds like in order to experiment w/ that:
A) we'd have to have a big problem we can't overcome w/ RNN v2
B) see a very good reason for making the switch (performance? stability? well maintained repo? one of those reasons probably)
(At the moment not having side menu UI baked in makes me think that we'll have even more work to do)
C) this project getting more stable maintenance and becoming more mature, so that we can feel that we can rely on it. RNN has the wix team behind it, it's faaaar from perfect, but lot's of people have used it (and/or banged their heads against the wall with it) but we know works.

Also between now and react-native fabric, I think it's wise not to make any big decisions, many things may change after that lands.

That being said, I can't express how grateful I am for having people like you creating such awesome and ambitious solutions.

**Comment by grahammendick** [comment]
Thanks for the thoughtful response.

I haven’t included a side menu component because it doesn’t involve navigating.  It should be a component that you include inside your scene. That way you can pass data to and from the side menu just like you would with any other component. Have you seen React Native’s [side menu component for  Android](https://facebook.github.io/react-native/docs/drawerlayoutandroid#rendernavigationview). It only works on Android because iOS doesn’t have a native drawer API. 

Is there any reason you think a side menu is better baked into the navigation library?

**Comment by SudoPlz** [comment]
@grahammendick I'm definitely not the right person to speak about that.
Not sure what the up/down sides of having that component on the native side are, but in our case because we're using it on both iOS and Android we'd have to implement it some other way.

**Comment by grahammendick** [comment]
Don't know why the React Native community hasn't made an `DrawerIOS` component that shows a `UIViewController` on the native side. Perhaps it's because people either know iOS or React but not both?

**Comment by SudoPlz** [comment]
^ probably!

**Comment by grahammendick** [comment]
Just to keep you updated, I've released a `TabBar` component that works on Android as well as iOS. It uses the native platform-specific APIs - a `ViewPager` on Android and a `UITabBarController` on iOS.
