### ISSUE TITLE
Slight delay of rendering during screen navigation

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#268]
There's a delay of rendering during screen navigation, especially during the navigation animation.
Even if I don't use animation the delay is still noticeable, causing a quick flicker of white screen.

**Comment by grahammendick** [comment]
Upgrade to the latest `navigation-react-native` and the delay will go away.

In the older versions of `navigation-react-native` I did the navigation before the render happened. Ever since v5.0.0 the render happens before I do the navigation. You don’t get any flicker of a blank screen because the screen is rendered before the navigation starts. 

With the latest version there’s no longer native setup required. You should revert the setup changes to `AndroidManifest.xml` (Android), and `AppDelegate.h` and `AppDelegate.m` (iOS). Take a look at the updated [setup guide](https://grahammendick.github.io/navigation/documentation/native/setup.html) for the JavaScript differences.

**Comment by SatyaFariz** [comment]
I have upgraded to the latest version and the flickering does go away but the navigation is slightly delayed (not happening as soon as the user presses a button). Is it because the navigation waits until react finishes rendering all the components?

**Comment by grahammendick** [comment]
Make sure that [development mode is off](https://facebook.github.io/react-native/docs/performance#profiling) before you test the performance

**Comment by grahammendick** [comment]
I'll close this down, but if you experience any navigation performance issues when testing with development mode off then please raise an issue

**Comment by SatyaFariz** [comment]
I have tested with dev mode off and the delay is still noticeable compared to v4

**Comment by grahammendick** [comment]
Ah, but v4 gave an unrealistic expectation because it started the navigation before the render. The behaviour of v5, by rendering before navigating, matches the behaviour of a real native app. Try out one of the native apps on your phone and I bet there's a similar delay before the navigation starts. That’s because real native apps also load the view before the navigation starts.

**Comment by SatyaFariz** [comment]
Ah I see
