### ISSUE TITLE
Android issue when app is killed in background

### ISSUE THREAD

**Issue by melkayam92** [grahammendick/navigation#314]
When the app is killed in the background, and then we reopen the app - we got this error:

![bug](https://user-images.githubusercontent.com/8774744/67161496-c42b6180-f363-11e9-9028-ae72d00e1463.png)

You can easily reproduce by going to developer settings and toggle 'Don't keep activities'.

I guess its something to do with the 
```
protected void onCreate(Bundle savedInstance) {
}
```

that tries to restore the old state of the app.

**Comment by grahammendick** [comment]
Thanks for raising. I'm testing on emulators so can't access the developer settings. Is there another way I can recreate? Or, even better, would you like to work on this? I've got some ideas of things we could try. You'll find out about the unique way that the Navigation router remembers the stack.

**Comment by melkayam92** [comment]
Sure I can try if you want.

Can you provide me with an easy way to run my app with the package installed locally so I could easily test it against new changes?
(For android it's easy) but the problem is the JS file which minified.

About this issue, it seems like adding to MainActivity:

```
    @Override
    protected void onCreate(Bundle savedInstance) {
        // super.onCreate(savedInstance);
        super.onCreate(null);
    }
```

resolve the issue and even the app gets back to his original scene which is great! but I think it's a workaround and maybe we should try to look at it more. Do you have any direction?

**Comment by grahammendick** [comment]
Thanks, It's great to have that workaround. That was going to be the first part of the investigation! 

## Working locally
Run `npm install` from the top level project folder to install the build dependencies. After making your code changes, run `npm run package`. This generates a `navigation-react-native` folder inside the `build/npm` folder. Copy this `navigation-react-native` folder into the `node_modules` of any of the [samples](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample) and you’re good to go.

## Investigation
With your workaround in place, I’m interested in what happens  on the React side when the app comes back to life. Does it restart the JavaScript environment? Put a [console.log in App.js](https://github.com/grahammendick/navigation/blob/7d78c28980614ec3197a3a3451dcc5a02e52e079/NavigationReactNative/sample/zoom/App.js#L14) and see if it recreates  the `StateNavigator`.

**Comment by grahammendick** [comment]
@melkayam92 Let me know if you're still interested in working on this. The investigation above is only the first step. There are more interesting steps to come once we know the answer to that first one

**Comment by melkayam92** [comment]
@grahammendick I also have a hard time reproducing it locally, just on release mode.

I think the workaround is good for now since a lot of libraries suffer from this.

**Comment by grahammendick** [comment]
Ok. Here’s the rest of the investigation for future reference:

We want to save the ‘state’ of the Navigation router and restore it when the app is restarted so that the stack is preserved. The ‘state’ of the Navigation router is held in a single `url` property
```js
const url = stateNavigator.stateContext.url; 
```
In the [zoom example](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/zoom) when the app loads the url property is '/grid'. Then when you pick the color 'orange', for example, it changes to '/detail?color=orange&crumb=%2Fgrid'.  Notice that the url contains the  'grid' scene as well as the 'detail' scene. The url holds the full stack of scenes.

So to store the 'state' of the Navigation router, we just have to save the url property whenever we navigate. Then when the app restarts we retrieve our cached url property and navigate to it.
```js
//retrieve the stored url property
stateNavigator.navigateLink(url);
```
This will open the app with the full stack of scenes restored. In the zoom example, if we pass '/detail?color=orange&crumb=%2Fgrid' to `navigateLink` then it will navigate to the color 'orange' detail page.

**Comment by grahammendick** [comment]
I recreated this in an emulator by changing the language via settings (thanks to #409).

In my testing, the UI state is restored automatically by a combination of React Native and the Navigation router. React Native keeps the JavaScript environment alive when the app is backgrounded. The Navigation router remembers what scene the user is on because the App renders with the old stateNavigator when it's foregrounded again.
