### ISSUE TITLE
iOS large title animation issue

### ISSUE THREAD

**Issue by emerson233** [grahammendick/navigation#334]
A strange behavior in `zoom` sample, see below:
![output](https://user-images.githubusercontent.com/42024893/69233406-cf261b80-0bc7-11ea-8cf8-3f090264fe4e.gif)

`NavigationBar` is jumping after clicking back button.
This is frustrating because it occurs only when using non-English character in `title` props (such as "Росси́я" in Russian, "我的" in Chinese).
Seems like a bug on iOS itself?

**Comment by grahammendick** [comment]
Make sure this happens on a real iPhone because the Xcode simulator isn't 100% trustworthy. If it does happen on a real iPhone, then you should check if it is a bug on iOS itself.  You can download [the iOS search code sample](https://developer.apple.com/documentation/uikit/view_controllers/displaying_searchable_content_by_using_a_search_controller?language=objc) to help get you started.

**Comment by emerson233** [comment]
Tested. It was happening in a real device as well.
I wrote a demo in pure Swift code for this. Simply set a NavigationController as rootViewController. It's ok to push/pop with large title (setting non-English character)
![output2](https://user-images.githubusercontent.com/42024893/69236667-f9c7a280-0bce-11ea-8bbb-35723f506290.gif)
It's nothing about `SearchController`. Removing it doesn't change anything.

**Comment by grahammendick** [comment]
With React Native, the UINavigationController isn't the rootViewController. The rootViewController is a UIViewController and then the UINavigationController is added as a subview. Can you try that out with your swift example and see if it still works fine, please?

**Comment by grahammendick** [comment]
I think it's some kind of iOS bug. I downloaded the [iOS search code sample](https://developer.apple.com/documentation/uikit/view_controllers/displaying_searchable_content_by_using_a_search_controller?language=objc) and it behaves oddly when the title is "我的", Although it doesn't jump, it shows the small title instead of the large one when navigating back.

**Comment by grahammendick** [comment]
I've tried a lot of different prop combinations have come up with a workaround. Try adding the following `contentOffset` and `contentInset` props
```jsx
<Container
  style={styles.scene}
  collapsable={false}
  contentOffset={{x: 0, y: -10}}
  contentInset={{top: 10, left: 0, bottom: 0, right: 0}}
  contentInsetAdjustmentBehavior="automatic">
```

**Comment by emerson233** [comment]
Work like a charm. Truly appreciate your effort.
