### ISSUE TITLE
Use BottomNavigationView instead of top tabs for BottomTabs on Android

### ISSUE THREAD

**Issue by mpiannucci** [grahammendick/navigation#339]
Currently bottom tabs are hacked on using a `TabLayout` instead of using the Material `BottomNavigationView`. There are a few important differences between the two and I will try to demonstrate with the twitter example app and the real work Twitter app on Android. 

On Android bottom tab bars should follow [the material design spec](https://material.io/components/bottom-navigation/#usage). They do not use a swipeable fragment pager, but rely on the button to transition between tabs. This may seem small but it shows when you compare the current way this library works with the Official Twitter App: 

![Screenshot_1577388337](https://user-images.githubusercontent.com/1832671/71487866-a0651b80-27eb-11ea-8638-062873d17b19.png)

As you can see they have top tabs embedded within the fragments showing on the bottom. This is how a ton of android apps work. 

Furthermore, the sizing is wrong and there is currently no way to get rid of the indicator bar on the tab view in this library.

So in total, the height is different than what a native bottom tab bar should be, there shouldnt be a line indicator by default on bottom tabs and the child views should not be swipeable to allow for their children to have top tab views. 

I am willing to work on this, but since its a pretty big change I assume you will have some preferences in how it is implemented. Let me know any feedback you have!

**Comment by grahammendick** [comment]
Seasons greetings! Thanks for such a detailed and interesting issue. 

There’s another difference between the tabs in the twitter example and the real Twitter app. The tabs in the real Twitter app don’t have separate stacks. In fact, as soon as you tap a tweet on the Home tab then you can’t go to the Search tab until you navigate back. Even in other Android apps where the bottom tabs are always visible, it’s unusual for the bottom tabs to have their own separate stacks. You expect to return to the start when you change the bottom tab.

We can already create bottom tabs like in the real Twitter app with the Navigation router. We create one `State` for each bottom tab. We set `trackCrumbTrail` to false (the default) so that the stack starts from scratch when changing tabs. Then we render a single stack with our bottoms tabs below it. 

```jsx
const stateNavigator = new StateNavigator([
  {key: 'home'},
  {key: 'search'}
]);

<View style={{flex: 1}}>
  <NavigationHandler stateNavigator={stateNavigator}>
    <NavigationStack />
  </NavigationHandler>
</View>
<View style={{height: 48}}>
  <Button title=”Home” onPress={() => stateNavigator.navigate('home')} />
  <Button title=”Search” onPress={() => stateNavigator.navigate('search')} />
</View>
```
You can create a custom component for the tabs so that they render as a `BottomNavigationView`. But I don't think that should be part of the Navigation router.

**Comment by mpiannucci** [comment]
Yeah that’s where this library departs from Android usage: typically tabs don’t have their own stacks on Android.

I will just wrap BottomNavigationView myself probably then, I just figured since the tab bar could be placed on the bottom it would be smart to use the correct native component to do so

Thanks and happy holidays!

**Comment by grahammendick** [comment]
I‘ll document my proposed solution for the typical single-stack Android bottom tabs.

Do you think the Navigation router should have a component that renders to `BottomNavigationView`?

**Comment by mpiannucci** [comment]
I am not sure yet thinking about your comment. Let me try to prototype up something and see how it comes out

**Comment by mpiannucci** [comment]
So I played around a bit. I get why this is a hard problem now. It’s really easy to wrap a BottomNavigationView but it’s different enough from the existing TabBar functionality: no swiping between fragments, no keeping the bottom tabs on route changes. 

I think people will expect this to exist but you are right in explaining why it doesn’t exist so far. Me personally I require the native bottom tab bar for my app so I will just wrap it myself for now.

**Comment by grahammendick** [comment]
You've changed my mind, the Navigation router does need to support the bottom tab pattern. I’ve got a design idea that I want to run past you. With the current `TabBar` design each `TabBarItem` has its own navigation stack. 

```jsx
<TabBar>
  <TabBarItem title=”Home”>
    <NavigationHandler stateNavigator={homeStateNavigator}>
      <NavigationStack />
    </NavigationHandler>
  </TabBarItem>
  <TabBarItem title=”Search”>
    <NavigationHandler stateNavigator={searchStateNavigator}>
      <NavigationStack />
    </NavigationHandler>
  </TabBarItem>
</TabBar>
``` 

This works well for swipeable sub tabs but not for the bottom main tabs. We can change the `TabBar` so it can also work with a single navigation stack. Instead of each `TabBarItem` having a child navigation stack, we can make the navigation stack a direct child of the `TabBar`. 

```jsx
<TabBar>
  <NavigationHandler stateNavigator={stateNavigator}>
    <NavigationStack />
  </NavigationHandler>
  <TabBarItem title=”Home” />
  <TabBarItem title=”Search” />
</TabBar>
``` 

Then we can render a `ViewPager` in the first scenario (current implementation) and a `BottomNavigationView` in the second scenario.

**Comment by mpiannucci** [comment]
Great! That flow makes sense to me. For the bottom tab scenario you show how would the user switch the scene? Would they listen for the current tab to change and re render? Or would the tab bar item navigate to non-crumbtrail routes?

**Comment by grahammendick** [comment]
The user would listen for the onPress of TabBarItem and navigate to non-crumbtrail route.

**Comment by mpiannucci** [comment]
Sounds like a good solution to me. 

And then this would only be on android right? On iOS it would stay the same?

**Comment by grahammendick** [comment]
Yes, Android only. I'm glad you like it. Let me know if you want to work on it.

**Comment by mpiannucci** [comment]
I can take a look, but I have to make sure I understand how the current TabBar and TabBarItem native implementation works first so I can reuse as much as possible. I don't totally get all of the pieces yet

**Comment by grahammendick** [comment]
No problem. I'm not sure how to implement it yet either. We can work on the design together, maybe?

**Comment by mpiannucci** [comment]
Sounds good to me

**Comment by grahammendick** [comment]
I've had an idea. Why don't we always render it the same way with a stack per tab? Then on Android the user can add an `onPress` and navigate to the first state. That way the tab will always start a new stack when it's tapped.
```jsx
<TabBar>
  <TabBarItem title=”Home”  onPress={() => {
    if (Platform.OS === 'android')
      stateNavigator.navigate('home')}
  }>
    <NavigationHandler stateNavigator={homeStateNavigator}>
      <NavigationStack />
    </NavigationHandler>
  </TabBarItem>
  <TabBarItem title=”Search”  onPress={() => {
    if (Platform.OS === 'android')
      stateNavigator.navigate('search')}
  }>
    <NavigationHandler stateNavigator={searchStateNavigator}>
      <NavigationStack />
    </NavigationHandler>
  </TabBarItem>
</TabBar>
```
So, the `TabBar` component already supports this! Perhaps we don't need to do much at all. Couldn't we stick with rendering a `TabLayout` instead of a `BottomNavigationView`? I'm thinking we could just add props to disable the swiping and remove the indicator. Would this work?

**Comment by mpiannucci** [comment]
The only issue that I have is that the BottomNavigationView has some subtle animations that I dont think the tab bar has. 

I started trying to prototype in a different way, where the bottomtabbar component is nothing but the bar just to try to get the rendering of TabBarItem as children to work.

**Comment by grahammendick** [comment]
Ok, let's add a `swipeable` prop to the `TabBar`. It defaults to true and renders a `TabLayout`. But if it's set to false then it renders a `BottomNavigationView` instead. 
So there's always a stack per tab but we leave it up to the user to decide if the stack resets on changing tab.

**Comment by grahammendick** [comment]
I've taken another look at the real Twitter app and the tabs are only visible on the start States. So there's no need to reset the stack onPress because the stack has to be at the beginning to change tabs. If this is the android standard then we just need to add a `swipeable` prop and render a `BottomNavigationView` if true.

**Comment by mpiannucci** [comment]
Okay that sounds good. 

I started trying to get the bar to render with TabBarItems as children and that works except for the images. Idk why but I cant get the image uri to load. If you want to take a look at how I started nad try something the code is here https://github.com/grahammendick/navigation/compare/master...mpiannucci:bottom_tabs_android?expand=1

**Comment by mpiannucci** [comment]
Sorry missed your earlier comment. Yeah that is the android standard, tabs stay on top level.

**Comment by grahammendick** [comment]
Thanks for the code sample. It helped me think through the problem. I’ve got a clearer idea of the solution now. Let me know what you think.
## Spec
We’ll add a `swipeable` prop to the `TabBar` component. This will default to true so that it’s backward compatible. If it’s false then, instead of rendering a `TabLayout`, we’ll render a `BottomNavigationView`. We’ll do this conditional rendering in the javascript. The `TabBar` component will check the `swipeable` prop and either render a `NVTabLayout` or a `NVTabNavigation` native component. The rest of the `TabBar` javascript stays the same. 

On the native side we’ll create a `TabNavigationView` that inherits from `BottomNavigationView`. We don’t want the `TabBarView` to worry about how the Tabs are rendered so we’ll create a `TabView` interface. Both the existing `TabLayoutView` and the new `TabNavigationView` will implement this interface. The `TabBarView` will talk to this interface instead of talking directly to the `TabLayoutView` like it currently does. An example interface method is `setupWithViewPager`. 

If swipeable is set to false then the `TabBarView` component will disable the swiping functionality of the `ViewPager`. 

We’ll add a `hideTabs` prop to the `TabBar` component. If set to true then it won’t render the tabs.

**Comment by mpiannucci** [comment]
Sounds like a solid plan to me!

**Comment by grahammendick** [comment]
Great! I’ve created #341 that implements this basic spec. If you run up the Twitter example and set `swipeable` to false on the `TabBar` component then it will render a `BottomNavigationView`.

I’ve listed all the tasks I can think of in the PR description. Let me know if I’ve missed anything. If you’re interested in working on any of them then create a branch from my PR branch and I’ll merge your work in.

**Comment by mpiannucci** [comment]
Great!!! I will add features as I can and add PRs for you. Happy New Year!

**Comment by grahammendick** [comment]
Happy New Year. This issue means my 2020 has started with a bang

**Comment by arunmenon1975** [comment]
Quite an Interesting discussion for a useful feature to a core router component.

Sorry for intruding in but i wanted to add something that perhaps could be of value during these early 'discussion' days, and this is feedback from a live/ongoing dev implementation. 

My app (and indeed the original Twitter app as well, in the inner screens) has a top `NavigationBar`, a `TabBar` positioned below it and a static/js `BottomNavigation bar/view` at the bottom. Everything works fine: the router is withstanding my shoddy efforts thus far without any issues (in my defense, i am still in development and there are other features that needs attention so i left the optimisations for later). 

But there is one niggling feature that is slightly challenging to implement without using minimally some form of global state management. The Twitter app handles it well as does several others, including the Play store app (which sometimes has an additional tab layer as well for a total of four). It is the autoscroll out-of-view/into-view capability of the `NavigationBar` equivalent depending on the vertical scroll direction inside of the `TabBar` content. It seems to be a common enough feature in most well-developed apps that have at least 3 constant 'bars' on screen. 

Since the router now has all these 'bars' shipped along, i was wondering if this feature could be given some thought and perhaps some synergy could be shared across these components since they are all owned by the router. I am not sure how though. Maybe the `TabBar` always exposes the current `Y` scroll amount that could be consumed by the top `Navigation` bar or any other component in fact. One straightforward implementation that i came across - that uses `Reanimated` for a better performance - is at [https://github.com/rgommezz/reanimated-collapsible-navbar/blob/master/App.js](https://github.com/rgommezz/reanimated-collapsible-navbar/blob/master/App.js).

**Comment by grahammendick** [comment]
@arunmenon1975 Happy New Year. Thanks for the idea. My first thought is we should use [Android's native Collapsing Toolbar](https://material.io/develop/android/components/collapsing-toolbar-layout/) implementation. Would you be interested in investigating it?

**Comment by arunmenon1975** [comment]
Thanks, and Happy New Year to you as well! 

Yes, and i just did some preliminary investigation as well since i am hindered by the fact that i am not a native dev as such.

The native Android feature is definitely a better option but i think, from early checking, it may be a little more complex than just adding a container view with presets into the router native code.

For a bare-basic support, from what i understood, two new container views will need to be introduced. The overall `CoordinatorLayout` view that wraps everything and the new `CollapsingToolbarLayout` view that will have the existing `Toolbar` as a direct last-child descendent.

So will that mean that the `NavigationBar` class will now have to extend `CoordinatorLayout` and not `AppBarLayout`? And then use the `addView` method to add the required hierarchy?

```
public class NavigationBarView extends CoordinatorLayout {
    private IconResolver iconResolver;
    Toolbar toolbar;
    AppBarLayout appBarLayout;
    CollapsingToolbarLayout collapsingToolbarLayout;

.....

public NavigationBarView(Context context) {
        super(context);

        toolbar = new Toolbar(context);
        appBarLayout = new AppBarLayout(context);
        collapsingToolbarLayout = new CollapsingToolbarLayout(context);
        addView(appBarLayout, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        addView(collapsingToolbarLayout, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        addView(toolbar, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
 ......

```


Additionally, please let me know if i need to move this to a new issue. I commented here since i really wasn't sure then where it could fit in. My thought-process was more on the lines of the `TabBar` possibly exposing props with `Y` values or something like that and since there were proposed changes to the `TabBar` maybe it was the right issue after all.  It does seem off-context considering the title of the issue though.

**Comment by grahammendick** [comment]
@arunmenon1975 Yes, please move it to a new issue and I'll reply to you there
