### ISSUE TITLE
I think this library can be so much more

### ISSUE THREAD

**Issue by hhunaid** [grahammendick/navigation#340]
Hello,

I have been following the repo for quite some time and I really want to use it in my new or existing projects because I have seen what native navigation stack can do for app performance. But there are certain features that are lacking that keeps me from adopting it. 
Side Drawer in iOS and true bottom tab navigation in Android to name a few.
I understand the reasoning behind not adding them because they are not 'native' but this kinda goes against the spirit of RN. 
I think we should not close off a door on a feature that a lot might benefit from. Sure side drawers are not a thing in official iOS specs but a lot of people choose RN because you get to share designs, code, and behavior of the app. I would need to make separate designs for iOS and Android if I were to use this package because certain features are not available in one platform or the other. You added shared element transition on iOS (at least I think you did) so why not other stuff?
Sure there are alternatives like RNN but they are unreasonably bloated. The code design is not react-like at all and it breaks with every couple of RN releases.

A lot of people including myself will be willing to add these features. We don't need to compete against RNN in the feature list. We just need enough features so people can use this library without having to use hacks for some basic UI components that most apps today have.

**Comment by grahammendick** [comment]
Hey, thanks for getting in touch. I’m confident you can start using the Navigation router on your projects because it does support Side Drawer on iOS and Bottom Tabs on Android. 

You can use any Side Drawer library with the Navigation router. For example, the [Drawer Layout from React Native Gesture Handler](https://software-mansion.github.io/react-native-gesture-handler/docs/component-drawer-layout.html) works great.

The library doesn’t come with a Bottom Tab component because you can make one out of a `NavigationStack` and one `Button` for each tab. The initial `States` for each tab have `trackCrumbTrail` set to false (the default) so that the stack starts from scratch when switching tabs.

```jsx
const stateNavigator = new StateNavigator([
  {key: 'home'},
  {key: 'search'}
]);

<View style={{flex: 1}}>
  <NavigationHandler stateNavigator={stateNavigator}>
    <NavigationStack />
  </NavigationHandler>
</View>
<View style={{height: 48}}>
  <Button title=”Home” onPress={() => stateNavigator.navigate('home')} />
  <Button title=”Search” onPress={() => stateNavigator.navigate('search')} />
</View>
```

**Comment by grahammendick** [comment]
Good news! With the release of navigation-react-native 6.5.0, the [TabBar component is fully cross-platform](https://grahammendick.github.io/navigation/documentation/native/tab-bar.html). What’s more, it’s 100% native on Android. It renders as a `ViewPager` and either a `BottomNavigationView` or a `TabLayout` depending on whether you’re designing bottom or inner tabs. You can see it in action in the [Twitter sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter).
