### ISSUE TITLE
Allow trailing slashes in links.

### ISSUE THREAD

**Issue by SiAshbery** [grahammendick/navigation#349]
Hi,

First off thank you, really appreciate the package as it solves a lot of problems for us.

However I've come across a conflict between `navigation`, `navigation-react` and the way our site is set-up and hosted.

Currently the behaviour is that `NavigationLink`s created with `navigation` do not have trailing slashes, the desired behaviour for us though is that we do have trailing slashes as this matches the folder structure for our site and we wish to keep urls consistent.

I was wondering if this is something I can already configure in `navigation` (in which case apologies as I seem to have missed it.)? Or if this is something you have or would consider adding?

Thanks.

**Comment by grahammendick** [comment]
Hey, I’m really glad you’re enjoying the Navigation router and thanks for getting in touch.

You can ensure `NavigationLinks` have trailing slashes. But don’t forget that a user can type a url without the trailing slash into the search bar. That’s why this might be better handled at the proxy server level by rewriting the path. Anyway, I’ll tell you how to add a trailing slash so you can decide what approach you prefer

You need to create your own `HistoryManager` and append the slash in the `getHref` function. Don't copy this code exactly because your `getHref` will need to cater for the querystring.
```js
class TrailingSlashHistoryManager extends HTML5HistoryManager {
  constructor(spplicationPath) {
    super(applicationPath);
  }

  getHref(url) {
    return super.getHref(url) + ‘/’;
  }
}
```
Then pass your `TrailingSlashHistoryManager` into the `StateNavigator` constructor.

```js
var stateNavigator = new Navigation.StateNavigator([
  {key: 'inbox', route: ''},
  {key: 'mail'},
], new TrailingSlashHistoryManager());
```

**Comment by SiAshbery** [comment]
Hi thanks for the quick response.

This has worked perfectly. Rewriting the URL in nginx was my first port of call but I was butting up against a conflict with S3, this fix will suffice for now but I will explore a proxy based solution.

Thanks again.
