### ISSUE TITLE
The distance parameter must be greater than zero and less than or equal to the number of Crumbs (0)

### ISSUE THREAD

**Issue by gabrielbull** [grahammendick/navigation#352]
I'm moving this issue out of [Several android crashes #348](https://github.com/grahammendick/navigation/issues/348) so we can focus on it.

I tried what you mentioned and use navigation state from context only but apparently users still experience this issue. I can reproduce only when clicking like crazy all over the app so it may be hard to find a way to reproduce reliably.

```
Error The distance parameter must be greater than zero and less than or equal to the number of Crumbs (0) 
    index.android.bundle:750:20307 getNavigationBackLink
    index.android.bundle:749:1208 navigateBack
    index.android.bundle:752:881 
    index.android.bundle:466:1047 b
    index.android.bundle:466:477 C
    index.android.bundle:466:825 E
    index.android.bundle:466:1239 goBack
    index.android.bundle:784:443 
    index.android.bundle:214:2263 touchableHandlePress
    [native code] touchableHandlePress
    index.android.bundle:205:9675 _performSideEffectsForTransition
    [native code] _performSideEffectsForTransition
    index.android.bundle:205:8357 _receiveSignal
    [native code] _receiveSignal
    index.android.bundle:205:5645 touchableHandleResponderRelease
    [native code] touchableHandleResponderRelease
    index.android.bundle:89:1197 b
    index.android.bundle:89:1340 k
    index.android.bundle:89:1394 C
    index.android.bundle:89:1692 N
    index.android.bundle:89:2482 A
    [native code] forEach
    index.android.bundle:89:2282 z
    index.android.bundle:89:13914 
    index.android.bundle:89:88659 _e
    index.android.bundle:89:13582 Ne
    index.android.bundle:89:13755 Ue
    index.android.bundle:89:14547 receiveTouches
    index.android.bundle:25:3685 value
    index.android.bundle:25:841 
    index.android.bundle:25:2939 value
    index.android.bundle:25:813 value
    [native code] value```

**Comment by grahammendick** [comment]
I’m confident that this should only happen if you use the `stateNavigator` from App.js instead of the one from React context. From the stack trace it looks like you’ve got a `goBack` JavaScript function. Can you show me the code of this function, please?

**Comment by grahammendick** [comment]
The error here is saying that you’re trying to navigate back but the stack isn’t big enough. Let me explain why I’m confident this error can’t happen if you use the state navigator from React Context.

Let’s say you navigate from Scene A to B to C. The Navigation router isolates each scene by giving them their own state navigator in React Context. Scene A’s state navigator thinks that Scene A is the top of the stack. Scene B’s state navigator thinks Scene B is the top of the stack. And Scene C’s state navigator thinks Scene C is the top of the stack. Only the state navigator you created in App.js has the overall picture. It knows that Scene C is really at the top of the stack.

![idempotent-navigation](https://user-images.githubusercontent.com/1761227/73658620-8e995280-468c-11ea-935e-e8888eb66a4e.png)

Now, let’s say you have a button on Scene C that navigates back one. If you press this once then you’ll go back to Scene B. But what happens if you press it twice? Will you go back to Scene A? No. You’ll still go back to Scene B. Even if you press it 10 times, you’ll only go back to Scene B. That’s because Scene C’s state navigator is immutable. It doesn’t change when you tap the back button. Only the state navigator in App.js changes.

Please can you check again that you’re always using the state navigator from React Context?

**Comment by gabrielbull** [comment]
You're right, there are some instances where I navigate back from external functions, in my case, redux-sagas, I also noticed I did not put a condition with `stateNavigator.canNavigateBack(distance)` before so I will try to add this first. My bad.

**Comment by grahammendick** [comment]
Thanks for checking again. Remember that you don't need `canNavigateBack` checks if you use the state navigator from React Context. 

Also, did you know that you can access the stack in JavaScript as an array of `crumbs`? Each `crumb` holds the state and navigation data. This can help you make decisions about whether you really want to navigate back.
```js
const {crumbs} = stateNavigator.stateContext.
```
I'm closing this but let me know if you have any questions.
