### ISSUE TITLE
Cannot anchor ActionSheetIOS to BarButton on iPad

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#441]
Hi there,

I have a use case to display an Action Sheet upon tapping a BarButton. On iPhone, this works fine, since the Action Sheet just comes up from the bottom of the screen.

On iPad, however, the Action Sheet by default appears in the middle of the screen.

![Screen-Recording-2020-08-26-at-0](https://user-images.githubusercontent.com/6651364/91284144-6d609680-e783-11ea-90e7-531a73afda0d.gif)

There is a way to "anchor" it to a node, but that requires using `findNodeHandle` from a ref, and the BarButton is a function component. When I update the BarButton to use `React.forwardRef`, it does... something, but now the Action Sheet is anchored to the top of the screen.

![Screen-Recording-2020-08-26-at-1](https://user-images.githubusercontent.com/6651364/91284162-72254a80-e783-11ea-89eb-7c6ea2b205c5.gif)

Here is the desired behaviour, from Mail:

![IMG_13BA2A721BA5-1](https://user-images.githubusercontent.com/6651364/91284745-3a6ad280-e784-11ea-8dd5-a8373ca27841.jpeg)

Any thoughts? Seems like it could be close to working, maybe something just needs to change with the frame? I've created a demo branch of this, here: https://github.com/salockhart/navigation/tree/ipad-action-sheet

**Comment by grahammendick** [comment]
Nice to hear from you. And with such an interesting one, too.

The alert controller (aka action sheet) can be positioned using a view or a barButtonItem. See the ["Specifying the Popover's Anchor Point" section](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller?language=objc). I guess the reason why they have both options is because barButtonItems aren't views (they inherit from `NSObject` not `UIView`). Unfortunately, react native doesn't accept a barButtonItem as anchor. Even if it did, `findNodeHandle` doesn't return the barButtonItem. It always returns the wrapper `NVBarButtonView`.

Perhaps we can trick it and position this wrapper view in exactly the same place as the barButtonItem? Then it doesn't matter that we're using the view instead of the button.  Inside `NVBarButtonView` and inside `didMoveToWindow` set the view frame from the button's frame. 
```obj-c
self.frame = [self.button valueForKey:@"view"].frame;
```
I haven't tried this code so it's probably wrong. But it's a rough idea to try. Can you give this a go?

**Comment by salockhart** [comment]
I gave it a try, and I think I'm nearing a solution. Let me put up a PR and we can continue the conversation there.
