### ISSUE TITLE
Unable to add testID to navigation components: TabBarItem, BarButton, etc

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#460]
As part of our application, we are writing automation tests using Detox. For that we need to be able to query for elements so that we can tap them.

Up to this point we'd been using text or testID in order to query for elements. Text works great for querying the tab bar items, but doesn't work as well if we want to query for a navigation bar button that consists of just an icon.

Would it be possible to modify these native components to apply a testID? Is that even the recommended way of doing it? We're hesitant to rely on text in all cases since we support a number of languages, and it would be helpful for our automation to be language agnostic.

**Comment by grahammendick** [comment]
That’s a good idea. It looks like if we pass the testID prop to native then React Native automatically attaches it to the view. Is this something you could try out?

One problem might be that the native view for a navigation bar button isn’t what we want to query. For example, on Android we actually want to check the menu item and, on iOS, we’re looking for a button in the navigation item. Does this matter?

**Comment by salockhart** [comment]
It seems to work with the vanilla react-native components just fine, but with the navigation-react-native ones I'm not seeing the updated `accessibilityIdentifier` like I would expect.

It's my understanding that components like `TabBarItem` and `BarButton` don't really "render" they just act like proxies to the native views, right? Maybe we need to have those take in the `testID` and pass it along to the proxied view's `accessibilityIdentifier`?

**Comment by grahammendick** [comment]
I think the TabBarItem, for example, does "render" on iOS (and sometimes on Android) - it renders to the tab content rather than the tab itself. Can you find the `NVTabBarItemView` in the View hierarchy on iOS and see if it has the `accessibilityIdentifier`?

I agree that it would be better to set the `accessibilityIdentifier` (iOS) and `tag` (Android) on the proxied views. Would that allows us to do the following? How does Detox work out what the text is?
```js
expect(element(by.id('homeTab'))).toHaveText('Home');
```

**Comment by salockhart** [comment]
Okay, got some findings by inspecting through Xcode/Flipper:

On iOS:
1. I can find the `NVTabBarItemView` but only for the `primary={false}` version. If `primary={true}` I don't see it get rendered and I don't see any view with the given `accessibilityIdentifier`. And in this case, the `NVTabBarItemView` is the container for the tab contents, not the tab itself, like you said.
2. I can find the `NVBarButtonView` and it does indeed have the identifier applied to the native view but not the proxied view.

On Android:
1. I can find what I assume are the views for the tabs, but I don't see any tags applied to them. You said above they might render sometimes, so maybe this is okay?
2. I cannot find the `BarButtonView`, and I don't see the `testID` for that component get applied anywhere as `tag`.

I'm not sure to be honest how Detox would work with that test. I'd need to get something in place and try running some tests against it. But I am not sure the requirement around verifying text, (selfishly) I would only be tapping on them in order to traverse the app.

Looking further into Android opened the can of worms which is then trying to apply tags to the overflow menu items, too. That may be easy or not depending how the effort to proxy the `testID`

**Comment by grahammendick** [comment]
Thanks, as always, for your hard work. 

> I would only be tapping on them in order to traverse the app.

That was an ‘Aha!’ moment for me. Believe it or not, I never realised you wanted to tap on them. It all makes sense now.

We definitely need to add the `testID’s` to the proxied views, otherwise we won’t be able to tap them (I realise you already knew this, but at least I’m caught up now). We can investigate what views we need to add them to by using the `by.type` Detox matcher. For example, can you check if this works for changing the tab?

```obj-c
element(by.type('UITabBarButton'))atIndex(1).tap();
```
It would be great if you could find the types for all tabs - primary false and true - and buttons on both iOS and Android. You can use the View hierarchy debuggers in XCode and Android Studio to find the type names, but maybe you can do it in Flipper too.

**Comment by salockhart** [comment]
Alright! We got some results.

I've pushed up a branch with some test cases if you'd like to look, the important file is here: https://github.com/salockhart/navigation/blob/96fdfc7c034eca9047e2ab8b9fa2237d2a952484/NavigationReactNative/sample/twitter/e2e/test.e2e.js

The gist of it is:

iOS:
* Tab (primary): UITabBarButton
* Tab (non-primary): UISegment
* Nav Button: _UIButtonBarButton

Android:
* Tab (primary): com.google.android.material.bottomnavigation.BottomNavigationItemView
* Tab (non-primary): com.google.android.material.tabs.TabLayout$TabView
* Nav Button: androidx.appcompat.view.menu.ActionMenuItemView
* Overflow Button: androidx.appcompat.widget.ActionMenuPresenter$OverflowMenuButton
* Overflow Menu Button: androidx.appcompat.view.menu.ListMenuItemView

Going through the Android ones, though, I wonder - would all possible consumers of this be using `androidx.appcompat`? Is there a risk that those are the classes for this specific app, but maybe not for a different one? I'm afraid I'm not well versed in these dependencies.

**Comment by grahammendick** [comment]
Thanks for the interesting results. This is a good baseline from which to start a PR. Are you happy to work on it?

We should use your results as a guide and look for simplifications where we can find them. For example, I checked react-native-navigation and they assign the [accessibilityIdentifier to the BarButtonItem](https://github.com/wix/react-native-navigation/blob/df745fe3423a8a4e9573fe31accf2379eb8fe4d6/lib/ios/RNNNavigationButtons.m#L259). If that works, even though the `BarButtonItem` isn’t in the view hierarchy, then I prefer that to looking for the `_UIButtonBarButton`. The [same applies to the TabBarItem](https://github.com/wix/react-native-navigation/blob/df745fe3423a8a4e9573fe31accf2379eb8fe4d6/lib/ios/RNNTabBarItemCreator.m#L24). 

Good spot with the overflow button. We need to create an `overflowTestID` prop for that. The overflow menu buttons might be tricky because they appear in a popup window. This is the can of worms you warned us about, but we can’t avoid opening it. 

> would all possible consumers of this be using androidx.appcompat

Yes. For example, we use the Toolbar component from androidx.appcompat so all its children will also come from that namespace.

There’s a couple of extra testID props we need. One for the navigation  icon to the left of the title on Android and another for the back button on iOS.

**Comment by salockhart** [comment]
I should be able to carve out some time to work on this starting this week. Thanks for passing those examples along, those will be super helpful.

**Comment by salockhart** [comment]
Some progress made today on iOS: Nav Bar Buttons and Tab Bar Buttons are working.

Thought, I'm having some issues with:
* Non-primary Tabs: Having some trouble with this one, and I think it may be a common issue? Could it have something to do with the `NVSegmentedTabView` being a `UIControl`, and maybe we don't get the right lifecycle methods? I don't see any analog to this in react-native-navigation.
  * https://stackoverflow.com/questions/22873524/unable-to-set-accessibilityidentifier-of-uisegmentedcontrols-segments
  * https://stackoverflow.com/questions/8833967/how-do-i-set-the-accessibility-label-for-a-particular-segment-of-a-uisegmentedco
* Back Button: This seems possible, but I am having some issues. [react-native-navigation does seem to handle it](https://github.com/wix/react-native-navigation/blob/df745fe3423a8a4e9573fe31accf2379eb8fe4d6/lib/ios/UINavigationController%2BRNNOptions.m#L65) but my main issue is retrieving a reference to the current navigation bar. In `NVNavigationBarView` I see how you grab the previous navigation item and set the title on that, but whenever I step through the debugger it's nil. Setting it anyway appears to have no impact, even so.

Have you got any insight into those issues? I will try to take a look at Android tomorrow

**Comment by grahammendick** [comment]
Great progress.

- For the primary tabs did you set the `accessibilityIdentifier` on the `UITabBarItem`? If that worked, I wonder if we can do the same for the non-primary tabs. 
- For the back button, we might have to do it a similar way to react-native-navigation. There is only one navigation bar so you can [get it directly from the navigation controller](https://github.com/grahammendick/navigation/blob/e4036e40fc39322ea3321e29987d89f2a817ee9b/NavigationReactNative/src/ios/NVNavigationBarView.m#L44)

**Comment by salockhart** [comment]
Thanks for your help - I think I've wrapped up the work on iOS. I'll be out on holiday next week so I will try to take a closer look at Android when I return.

Speaking of Android, I am seeing a compile error after updating the twitter sample with my latest changes. I run `npm run package && cp -r build/npm/navigation-react-native NavigationReactNative/sample/twitter/node_modules` in order to update it, and then I get the following errors in Android Studio. Is this something you've seen before? Maybe I've got a version mismatch? I haven't dug too far into it. It works just fine if I delete node_modules and reinstall, too, so it's got to be something in the copying.

```
failed
:navigation-react-native:compileDebugJavaWithJavac
    ../node_modules/navigation-react-native/android/src/main/java/com/navigation/reactnative/FragmentNavigator.java
        incompatible types: SceneFragment cannot be converted to SharedElementContainer
        incompatible types: SceneFragment cannot be converted to SharedElementContainer
        incompatible types: SharedElementContainer cannot be converted to SceneFragment
    ../node_modules/navigation-react-native/android/src/main/java/com/navigation/reactnative/SceneActivity.java
        incompatible types: SceneActivity cannot be converted to SceneFragment
    ../node_modules/navigation-react-native/android/src/main/java/com/navigation/reactnative/ActivityNavigator.java
        incompatible types: SharedElementContainer cannot be converted to SceneFragment
Compilation failed; see the compiler error output for details
```

**Comment by grahammendick** [comment]
Impressive. How did you get the non-primary tabs working on iOS?

Make sure you manually delete the android folder from `build/npm/navigation-react-native` before `npm run package`. You only need to do this when you've removed a java class (like probably happened since the last time you built the package). I meant to add this delete to the 'package' task but never got around to it.

**Comment by salockhart** [comment]
The non-primary tabs on iOS are... annoying. The result is that I end up assigning the identifier to the `UISegment`'s child (a `UISegmentLabel`, in our case) in the `layoutSubviews` phase. No matter what, I can't see to get it to stick to the `UISegment` itself. There's no `UITabBarItem` there for us to attach to like we do with the primary tabs. This was one of the messier pieces, to be honest.

If you're interested, I can put up a PR for just the iOS side of things, if you want to get eyes on sooner rather than later?

**Comment by grahammendick** [comment]
Ah, I forgot there wasn't a `UITabBarItem` for non-primary tabs. Congrats on getting it working. I'm still curious how it works for primary tabs when `UITabBarItem` isn't in the View hierarchy. Any idea how iOS does it?

It'd be great if you put up a PR so I can get an early view. I fully understand that it's a work in progress.

**Comment by grahammendick** [comment]
Thanks for the PR, it looks great and helps my understanding!

> I'm still curious how it works for primary tabs when UITabBarItem isn't in the View hierarchy

Turns out that iOS takes the accessibilityIdentifier from the UITabBarItem and sets it onto the UITabBarButton. Makes sense now!

**Comment by salockhart** [comment]
Hi again!

I've begun looking into the Android implementation, and I was wondering if you'd have some input. Most of my troubles are coming from the bottom tabs and from the nav buttons, and I think it's the same reason: both of those are built as menus, not as views, which makes it difficult to apply the tag to the actual view. Do you have any insight into how/where I may hook into that menu lifecycle?

Also, I see for the nav buttons we could optionally provide children to use as the view, is that right? So that may be another case we need to cover.

**Comment by grahammendick** [comment]
Welcome back! Hope you had a nice break.

Let's start with the tabs. Have you managed the non-primary tabs on android? If so, I think the bottom tabs (primary) might be similar. The `TabLayoutView` is for the non-primary and the `TabNavigationView` is for the primary. Both these classes implement the `TabView` interface.

The `TabBarItemView` class is the one that maps to the `TabBarItem` component. It’s the same class for both the top and bottom tabs. In fact, it doesn’t know whether it’s top or bottom because it talks to the `TabView` interface only. For example, take a look at [how the setIcon works](https://github.com/grahammendick/navigation/blob/eda7481ed5e12e764d8defe51ba0dff9e8026d58/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/TabBarItemView.java#L46). Both top and bottom tabs accept an image prop and the `TabBarItemView` passes that onto them via a call to the `TabView` interface’s `setIcon` method.

Then the `TabLayoutView` and `TabNavigationView` both have their own implementation of the `setIcon` interface method. The `TabLayoutView` one [finds the tab and sets the icon](https://github.com/grahammendick/navigation/blob/eda7481ed5e12e764d8defe51ba0dff9e8026d58/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/TabLayoutView.java#L144). The `TabNavigationView` [finds the menu item and sets the icon](https://github.com/grahammendick/navigation/blob/eda7481ed5e12e764d8defe51ba0dff9e8026d58/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/TabNavigationView.java#L111).

I guess there’s no setTag on a menu item? So take a look at the `removeBadgeIcon` method. It’s the same idea as the `setIcon` but this time the `TabNavigationView` [finds the touchable child view](https://github.com/grahammendick/navigation/blob/eda7481ed5e12e764d8defe51ba0dff9e8026d58/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/TabNavigationView.java#L123). This might be what you need to do.

**Comment by salockhart** [comment]
Thanks! It was nice.

That pointer to the `removeBadgeIcon` was exactly what I needed - got primary tabs working now!

Now: nav bar buttons. I have gotten a little further taking what I learned from the back button. I can reliably tag the overflow button, but:

* I am having difficulty ensuring that we apply the correct testID to the correct button, see: https://github.com/grahammendick/navigation/pull/464#discussion_r526092552 in the draft PR for some more context.
* I am completely at a loss on how to attach a tag to the overflow menu items - it only gets rendered after tapping on the overflow icon, and when it finally appears it's not a child view of the toolbar, but of the window. Maybe we can attach a listener for when the menu opens, and then grab the view from the root?

**Comment by grahammendick** [comment]
That's great, glad it worked out.

- Is it safe to get the `BarButtonView` at the same position? So if it’s the nth `ActionMenuItemView` will it’s associated `BarButtonView` be at `children.get(n)`? ([children](https://github.com/grahammendick/navigation/blob/eda7481ed5e12e764d8defe51ba0dff9e8026d58/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/ToolbarView.java#L49) is the list of BarButtonItems)
- I think we could have problems getting those pesky overflow items! Your idea sounds very sensible way to go

**Comment by salockhart** [comment]
* I would be hesitant since not all of the BarButtonView items would be in the nav bar, some of them would end up in the overflow menu. That's easy enough if we just filtered for `show="always"` but I'd be anxious about `show="ifRoom"`
* Sounds good, I will try to take a stab at it

**Comment by grahammendick** [comment]
Ah, I think I see what you mean. If we had the following then the first button wouldn't relate to an `ActionMenuItemView`. 
```jsx
<BarButton show="never" />
<BarButton show="always" />
```
Lol, I wish I'd never included "ifRoom". I left it in when porting the `ToolbarAndroid` from react native. It's more trouble than it's worth!

Perhaps we could filter for "always" and "ifRoom" and make the counts match. For example, if we only find 4 `ActionMenuItemViews` but there are 5 filtered `BarButtonViews` then we remove the last "ifRoom" from the list? Assuming that Android gives precedence to the first "ifRoom"

**Comment by salockhart** [comment]
Hmm that could work. Out of curiousity, do you know if the buttons marked with `ifRoom` would always be consistent? Or could they appear/disappear based on device orientation / length of the title?

I get the feeling that this is getting more into the weeds with edge cases - maybe in practice we don't need to worry about it, and we could always re-visit? I'll give the filtering a shot and go from there

**Comment by grahammendick** [comment]
From what I remember, they're not based on orientation. But I never tried changing the title! Yes, I'm happy if we treat "ifRoom"s as consistent.

**Comment by salockhart** [comment]
Alright! Another day, another update.

Your suggestion around how to handle the `always|ifRoom|never` seems to be working pretty well - I'm sure there are holes but I think it's reasonably solid.

The overflow menu though... wow. I've taken a couple of approaches:

1. Retrieve the `overflowButton` and attach our own click listener. Issue here is that the menu appears sometime after the click - so the menu views we care about aren't rendered yet. Also feels hacky since we end up removing the existing click listener, and then we have to open the overflow menu ourselves. Feels messy and error prone.
2. Attempt to use an `ActionBar.OnMenuVisibilityListener` which _may_ give us what we want, _if_ it gets called after the menu appears. But, as far as I can tell, we aren't using an ActionBar.

Any thoughts?

**Comment by grahammendick** [comment]
I look forward to your updates. Thanks for all the detail.

I don't think the Toolbar can be an ActionBar. I did try it a while back but ran into trouble because there can only be one ActionBar per Activity.

That overflow menu sounds v tricky. If we work out a way of listening to when the overflow menu is visible/rendered, can we get at the popup window to find the items?

**Comment by salockhart** [comment]
I imagine that if we can find a way to listen for the menu, we could find the views. My worry now is that I may not have the time to dedicate to trying to find that solution. 

I'm going to timebox it to the rest of today and tomorrow, but: would you be comfortable with what we have now, in terms of testID support?

There's a couple more things I need to wrap up like testing Left vs Right bar buttons and making sure the types are up to date, but I can't guarantee that I will be able to spend the time needed to solve the overflow menu, at least not right now.

**Comment by grahammendick** [comment]
I'm happy to leave out the overflow menu and with the level of testID support. 

Would you have time to work through and any PR review comments I find? There's no time pressure with any of this, of course.

**Comment by salockhart** [comment]
Okay, great. And yes, absolutely - any changes on the PR that I need to make are no problem at all!

**Comment by grahammendick** [comment]
Ok, that sounds like a plan, then. You let me know when the PR is ready for review.

**Comment by salockhart** [comment]
@grahammendick https://github.com/grahammendick/navigation/pull/464 should now be ready for review, thank you so much for your help!

**Comment by grahammendick** [comment]
It's been a total pleasure. Thanks for all your hard work!
