### ISSUE TITLE
[IOS] there shouldn't be a navigation bar if no component is provided ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#477]
![Screen Shot 2020-11-27 at 10 18 50 AM](https://user-images.githubusercontent.com/19273413/100426676-f2688e00-3099-11eb-9c28-b21ca6a1950e.png)

on IOS an navigation is visible by default and you need to render `<NavigationBar hidden />` to hide it.

also it doesn't animate correctly when going from a screen with NavigationBar hidden to another with it visible.

**Comment by grahammendick** [comment]
I encourage you to include a `NavigationBar` on every scene (even on android). A recent PR (#469), that adds a `StatusBar` component , assumes a `NavigationBar` is always there.

**Comment by a-eid** [comment]
I did notice the `StatusBar`, I tried it out but something was off, do u think you'll be able to keep the documentation up to date, I'd love to help out if possible ?

**Comment by grahammendick** [comment]
Could you tell me what's wrong with the animation when going from hidden to visible, please?

**Comment by a-eid** [comment]
@grahammendick I'll try making a native ios back, see how the animation works and create a new issue if need be.

do u think the docs is up to date ? I would love to help out if you want.

**Comment by grahammendick** [comment]
>  I'll try making a native ios back, see how the animation works

That's a good idea, thanks!

Yes, the docs are up to date. I make sure I update the documentation before a release. But, I don't document everything. In order to keep the documentation focused, I only document the main features. For example, take the StatusBar component. I added this recently but didn't document it. The reason is that the Navigation router works with the StatusBar component from React Native. I want people to use the React Native one if they're happy. But if they face problems then hopefully they'll raise an issue here and then I can point them at the Navigation router's StatusBar component. Also, the Navigation router's StatusBar component doesn't support animation yet so it's not a complete replacement for the React Native one.

I'm going to re-open this issue because I want to think more about whether I should hide the navigation bar if there's no component.  

Thanks for your offer of help. I have got a few issues that you can help out with. Let me know if you're interested

**Comment by a-eid** [comment]
> I have got a few issues that you can help out with. Let me know if you're interested 

absolutely, I would love to.

**Comment by grahammendick** [comment]
Great! Do you prefer working on iOS, android or React?

**Comment by a-eid** [comment]
I am definitely more proficient in JS & React but I don't mind working with IOS as well (I have some past experience with it.)

**Comment by grahammendick** [comment]
@a-eid Thanks again for your offer of help. I've created an issue #478 for you to work on. Please ask me any questions you want. I'm always happy to help.

The funny thing is, while writing up the issue, I saw another reason (performance) why I want to encourage people to always include a NavigationBar on their scene. So I will close this, after all!
