### ISSUE TITLE
[IOS] back button tint colors changes when swipe gesture is active ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#483]
I don't think this happens when navigation is embedded inside of a modal.

![Nov-29-2020 19-14-44](https://user-images.githubusercontent.com/19273413/100548766-45e40300-3277-11eb-979d-7a46324739de.gif)

**Comment by grahammendick** [comment]
This is an iOS issue, right? I couldn't find a way to change the color of the back arrow using the iOS 13 appearance. So I set the [tintColor on the navigationBar](https://github.com/grahammendick/navigation/blob/bbc35a340217ab4a9c3a2fd3a89efbb260697cdf/NavigationReactNative/src/ios/NVNavigationBarView.m#L47). But, as you can see, this doesn't behave the same when swiping back.

What happens when navigation is embedded inside a modal?

**Comment by a-eid** [comment]
@grahammendick if the navigation is embedded inside of a modal it doesn't suffer from this issue.

![Nov-29-2020 19-24-01](https://user-images.githubusercontent.com/19273413/100548912-74aea900-3278-11eb-8518-afd8721f5b21.gif)

**Comment by grahammendick** [comment]
But that's because the previous scene and the current one share the same tintColor. Do your scenes share the same tintColor outside of the modal?

**Comment by a-eid** [comment]
that's probably why, 

modal navigators do share the same tint color, the other one doesn't.

**Comment by grahammendick** [comment]
Is there a way to change the color of the back arrow using the [appearance from iOS 13](https://sarunw.com/posts/uinavigationbar-changes-in-ios13/)? If there isn't then I think it's an iOS bug

**Comment by grahammendick** [comment]
I'm closing this because this is what happens in a native iOS app if screen A and screen B have different tint colors for the back arrow
