### ISSUE TITLE
[Question] How to style SearchBar text & placeholder ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#492]
- I've notice that you can't change the color of the text inside of the Search bar. 
- the cursor color correspond to the `tintColor` on the NavigationBar.

**Comment by grahammendick** [comment]
Could you describe what you're trying to do and why? For example, what color you want the placeholder and text and cursor to be. Then we can have a think about the best way to get there

**Comment by a-eid** [comment]
I'm trying to style the `SearchBar` Text & placeholder style & font. it would be great if it could be styled the same way a react native `TextInput` is styled. to keep styling across the app consistent.

**Comment by grahammendick** [comment]
@a-eid Would you be interested in working on a PR that adds color and font styling to the SearchBar?

**Comment by grahammendick** [comment]
I'm closing this because I can't fix something without an actual use-case. I get the feeling (from the other issues you raised) that you were just doing some general testing but weren't actually using the Navigation router. I'd expect us to work through the PR together so I can make sure that what I'm doing works for your use-case. For example, would it be ok to change the text color but not the placeholder color? Would it be ok to change the text font but not the cancel button font?
