### ISSUE TITLE
NavigationBar spacing

### ISSUE THREAD

**Issue by cloudrco** [grahammendick/navigation#508]
Is there any way we can adjust the NavigationBar spacing? Specifically, horizontal padding/margin.

<img width="326" alt="Screen Shot 2021-01-30 at 12 06 21 AM" src="https://user-images.githubusercontent.com/64134460/106333339-2f3c4580-62d4-11eb-8b08-047cb694ac08.png">

**Comment by grahammendick** [comment]
Hi there, thanks for the question. Any reason you want to change from the native defaults?

**Comment by cloudrco** [comment]
It's for design purposes. Currently we have a list that is  ~8pt horizontally (eg: `marginHorizontal: 8`). If we were to align the list horizontally with respects to the default NavigationBar spacing, it will not meet our design spec requirements. I'm hoping this is doable.

**Comment by grahammendick** [comment]
Looks doable using [layoutMargins](https://developer.apple.com/documentation/uikit/uiview/1622566-layoutmargins?language=objc) (or `directionalLayoutMargins` to allow for language direction?)
```obj-c
[navigationBar setLayoutMargins:UIEdgeInsetsMake(0, 40, 0, 40)];
```
And here's what it looks like on the zoom sample

![Screenshot 2021-01-30 at 14 51 25](https://user-images.githubusercontent.com/1761227/106359426-a7bdf900-630a-11eb-8e21-5ff3d20b90bd.png)

**Comment by cloudrco** [comment]
Awesome! Thanks @grahammendick 👍

**Comment by cloudrco** [comment]
@grahammendick is this something you can add as a feature? Something like `<NavigationBar horizontalSpacing={8} verticalSpacing={8} ... />`

**Comment by grahammendick** [comment]
Do you want vertical spacing as well?

**Comment by cloudrco** [comment]
The vertical spacing can be kept as default. I just thought it be ideal to have that feature/option that vertical spacing can be adjusted as well. I think it's weird to have one prop (horizontalSpacing) be adjusted while  vertical spacing cannot. Maybe you can rename the prop to something else like:

`<NavigationBar edgeInsets={[0, 8, 0, 8]} />`

However, this is up to you. Whatever feels right for you. Vertical spacing can be left out as our app does not need that spacing. Thanks!

**Comment by grahammendick** [comment]
I’m thinking the props will be `marginStart` and `marginEnd`
```jsx
<NavigationBar marginStart={8} marginEnd={4} />
```
I like these names because it’s a mix of the names of the corresponding native primitives. On Android, they’re `contentStart` and `contentEnd` and on iOS they’re `layoutMargins`. Also, they match well to the React Native [marginStart](https://reactnative.dev/docs/layout-props#marginstart) and [marginEnd](https://reactnative.dev/docs/layout-props#marginend) layout props. Another reason to go for start and end instead of left and right is that the Navigation router works in right to left (rtl) languages. In the ltr direction the `marginStart` is the left hand margin but in the rtl direction `marginStart` is the right hand margin. 

I don’t want to do vertical spacing yet because it’s hard to work on it without an actual use-case. For example, for the top spacing we’d have to come up with one prop that works on both Android and iOS. What primitive does that prop map to? what name should it have? How does it behave when large titles are true? Does the spacing apply to action views on Android? etc. These are hard decisions to make without a concrete use-case.

**Comment by cloudrco** [comment]
Awesome! That should do fine. `marginStart` and `marginEnd` makes more sense. Thanks @grahammendick!

**Comment by grahammendick** [comment]
> It's for design purposes. Currently we have a list that is ~8pt horizontally (eg: marginHorizontal: 8)

@cloudrco the default [layout margins on iOS are 8 points](https://developer.apple.com/documentation/uikit/uiview/2865930-directionallayoutmargins). Can you double check whether your list aligns with the navigation bar spacing, please?

**Comment by cloudrco** [comment]
Sorry for the late response, but here is a sample output of the app.

<img width="324" alt="Screen Shot 2021-02-07 at 7 16 54 AM" src="https://user-images.githubusercontent.com/64134460/107198337-b316d000-6a40-11eb-8422-6066dbb2e441.png">

As you can see, it's a bit off with the list view.

**Comment by grahammendick** [comment]
Thanks for the screen shot, it helps a lot.

In React Native, the measurements aren’t in pixels. They’re in an absolute scale that gets converted into pixels depending on the pixel density of the device. For example, if you set a margin of 8 on an [iPhone 11 then that will be 16 pixels](https://reactnative.dev/docs/pixelratio#methods).

The Navigation Bar is a native component and so when UIKit says it has a margin of 8, they’re talking pixels. In the zoom example, I’ve given the container `ScrollView` a margin of 8 pixels. I’ve converted the 8 into pixels using `PixelRatio` from React Native.
```jsx
<Container
  style={{
    ...styles.scene,
    marginHorizontal: PixelRatio.getPixelSizeForLayoutSize(8),
  }}
```
Here’s what it looks like. To make it clearer, I’ve put a border of red around the container and justified the content with 'space-between'. You can see that the scroll view and the navigation bar line up.

![Screenshot 2021-02-13 at 12 05 07](https://user-images.githubusercontent.com/1761227/107849529-bf5dad00-6df3-11eb-9ea5-617e7c43f535.png)

I think measurements from a design spec refer to pixels rather than React Native’s units.

**Comment by grahammendick** [comment]
@cloudrco are you happy specifying your margin in pixels?

**Comment by cloudrco** [comment]
Hi @grahammendick, sorry I'll close this issue. You are right about utilizing PixelRatio, however what happens when our design spec changes (eg: 4pts horizontally)? How will we be able to scale the design here? Thanks for your guidance and effort.

**Comment by grahammendick** [comment]
Great news, I’m always happy to help!

If you were building your app without react native, it would be a lot more obvious what the platform defaults are and the cost of diverging from them. For example, you’d realise why the navigation bar looks the same on pretty much all iOS apps.

The aim of the Navigation router is to give you the same UX you’d get if you were building without react native. It makes you think twice about diverging from the platform defaults. So lets cross that 4pt bridge when we come to it
