### ISSUE TITLE
No crumbs when navigating using navigateLink

### ISSUE THREAD

**Issue by maman** [grahammendick/navigation#525]
Hi, I'm using this lib with a dynamically-generated `StateNavigator` such as:

#### Route definition file
```ts
export default [
	{
		key: 'home',
		route: '/',
        handler: loadable(() => import('./home')), // lazy-loaded route handlers
		
	},
    ...
]
```

#### createStateNavigator
```ts
export default function createStateNavigator(routeDef) {
    const normalizedRouteDef = routeDef.map(route => {
        if (route.route === "/") return {...route, route: ""}
        return {...route, trackCrumbTrail: true} // for other route, set trackCrumbTrail to true
    });
	const stateNavigator = new StateNavigator(normalizedRouteDef);
    routeDef.forEach(route => {
        stateNavigator.states[route.key].renderScene = () => route.handler
    });
}
```

#### simplified react native entrypoint
```ts
import routes from './routes.ts';

const stateNavigator = createStateNavigator(routes);
export default App() {
    return (
		<NavigationHandler stateNavigator={stateNavigator}>
			{/* override renderScene to wrap scene component with my implementation */}
			<NavigationStack renderScene={() => <AppProvider shell={...} />} />
		</NavigationHandler>
  	)
}
```

I'm able to perform stateNavigator.navigate() / stateNavigator.navigateLink() from inside my components, but when I do `stateNavigator.canNavigateBack(1)`, it always return false

e.g following scenario

1. app startup, navigate to home
2. navigate to '/another-route' using `stateNavigator.navigateLink('/another-route')` -> this will correctly open `another-route` scene
3. perform `stateNavigator.canNavigateBack` from `another-route` -> return false

is there something missing in my route config/implementations that make the breadcrumb isn't activated?

thanks for the help beforehand! also nice lib!

**Comment by grahammendick** [comment]
Hey, great to hear from you.

You should use `navigate` instead of `navigateLink`. With the Navigation router, you don’t hard-code links. You pass the key of the `State` and the data you want to pass.
```js
stateNavigator.navigate('another', { id: 12 })
```
The Navigation router will then build a stack (breadcrumbs) so you can navigate back.

**Comment by maman** [comment]
ah, ok it's working when I use `navigate`, thanks.

anyway, how should I use the `navigateLink` method?

(I suppose I can do something to parse out passed `href`/hardcoded links to conform with the `navigate` params since my use case requires support for hard-coded links, but I'm still curious about the `navigateLink` method use case 😄)

**Comment by grahammendick** [comment]
Thanks for changing the issue title. That’s very thoughtful of you

# How to parse hard-coded links
Yes, you can use `parseLink` to get the `State` and navigation data and pass them into `navigate`
```js
const { state, data } = parseLink(href)
stateNavigator.navigate(state, data)
```
But I want to explain how you can use this approach and still get strongly-typed data. Let’s take an example where the href is '/another-route?id=2'. Even though the id is a number, it will be a string when you get it from context.
```js
const { data } = useContext(NavigationContext)
const { id } = data // id === '2'
```
If you want the id to be a number when you get it from context then you can specify its type as a number.

```js
const stateNavigator = new StateNavigator([
  { key: 'another', route: ‘another-route', defaultTypes: { id: 'number' }, trackTypes: false }
])
```

Also, note that I set `trackTypes` to false. This is important even if you don’t want strongly-typed data (because you’re parsing links not generated by the Navigation router).

I want to repeat that none of this is necessary if you use `navigate` directly. For example, if you call `stateNavigator.navigate('another', { id: 2 })` then the id would automatically be a number when you get it from context.

# Use case for navigateLink
A good use case for `navigateLink` is where you’re deep linking from the web and you want to push more than one screen at once. Imagine the user was on screen A when they last visited your app. When they click the deep link you want their stack of screens to become A → B → C. You want to push screens B and C together.

You might think you could do that with 2 successive calls to `navigate` from scene A
```js
stateNavigator.navigate('B')
stateNavigator.navigate('C')
```
But that doesn’t work. The stack would be A → C because each scene has its own local, immutable `stateNavigator`. So even after navigating to B, A's local `stateNavigator` doesn’t change. Scene A still thinks it's at the top of the stack! So when it navigates to C the stack becomes A → C. This is called idempotent navigation. It means you can't accidentally push the same screen twice if the user double clicks a button. 

Instead, you could navigate to B from scene A and then immediately navigate to C from scene B. This would work but it would render both scenes B and C. This is bad for performance. You only want to render C to start with and not render B until the user navigates back. 

This is where fluent navigation comes in. Fluent navigation allows you to build the exact stack of scenes you want as a link. Then you can navigate them all in one go by passing it to `navigateLink`. In the example, the Navigation router only renders the top scene C. It doesn’t render scene B until the user navigates back to it.

```js
const link = stateNavigator.fluent(true)
  .navigate(‘B’)
  .navigate(‘C’).url
stateNavigator.navigateLink(link)
```

If any of this isn't clear please let me know. I'm always happy to help

**Comment by maman** [comment]
That was very clear, thanks! 😄

Anyway, I'm re-reading your posts on medium, and still had something else to discuss regarding this navigation library - do you have ways to have discussions other than Github issues? this might not be the best place, since what I want to discuss is not an issue

feel free to close this issue in the meantime, thanks again.

**Comment by grahammendick** [comment]
Great, I've [opened up discussions](https://github.com/grahammendick/navigation/discussions) and look forward to hearing from you
