### ISSUE TITLE
Inconsistent behaviour when passing props through a NavigationStack in navigation-react-native

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#554]
Hi, hope you're well

My team has noticed an issue recently introduced in `navigation-react-native` version `8.6.0`. Namely, when passing props all the way down from one screen, into a modal, into a navigation stack and then finally into another screen, we are seeing inconsistent behaviour.

The following can be seen at an example branch I have, here: 

### Background

Our team sometimes has need of a navigator that shows a single screen and no more. This is used for things like rendering a navigation title bar at the top of a modal. Here's an example: https://github.com/grahammendick/navigation/blob/af36d4d43cdf05001524729c757f936235354ab2/NavigationReactNative/sample/singlescreennavigator/App.js#L41

By then passing the screen as a child of `SingleScreenNavigator` or passing a render function to the `Screen` prop, one can have easy one-off navigators without too much boilerplate: https://github.com/grahammendick/navigation/blob/af36d4d43cdf05001524729c757f936235354ab2/NavigationReactNative/sample/singlescreennavigator/App.js#L117-L126

This has advantages over a standard Navigator setup for one reason: the parent component can pass props to the child directly

### <`8.6.0`

Prior to `8.6.0`, on both iOS and Android this would work with initial props, but subsequent updates to those props would not render inside the child single screen navigator's screen.

Replicable in my own project but not in the toy example provided is if the child screen is passed using a render function, instead of as a child:

https://github.com/grahammendick/navigation/blob/af36d4d43cdf05001524729c757f936235354ab2/NavigationReactNative/sample/singlescreennavigator/App.js#L129-L140

Doing it this way, the child would be able to receive updated props, likely because the way it is rendered in the scene changes - instead of passing a rendered component into the navigator, we pass a render function. I haven't yet been able to replicate this behaviour in the example project.

<details>
<summary>Videos</summary>

https://user-images.githubusercontent.com/6651364/147356852-f6666980-9dba-4547-b63a-9b26f0aa5ea8.mp4

https://user-images.githubusercontent.com/6651364/147356867-0e518965-cd12-43d9-9ae1-68a55830c12d.mp4

</details>

### >=`8.6.0`

Funny enough, with the release of `8.6.0` and also replicable in `8.7.0`, this has changed. Props now update correctly! But only on iOS. When you pass the screen as a child it works flawlessly. Passing the screen as a function works _okay_ but it is clear that something is unmounting and remounting it each time, since the spinner is no longer visible, meaning internal state gets destroyed.

<details>
<summary>Videos</summary>

https://user-images.githubusercontent.com/6651364/147359231-46786090-ee7b-4f02-a437-0c2ae8e74880.mp4

https://user-images.githubusercontent.com/6651364/147359228-e6abf440-3538-4f7b-a80b-9a6da1ea512f.mp4

</details>

### Questions

I realise this might be not-best-practice, so if the answer is "what are you doing, of course that is weird" then I value a suggestion to replace this! That said, my main questions are:

- [ ] Is this pattern doomed to fail, and are these inconsistencies a cost of that?
- [ ] If this pattern is valid, should we look at making the two platforms work consistently? Should they match the "no nav stack" example?
- [ ] How would you approach this problem? There is a lot of value in being able to pass props to a screen without it going through a navigator, but I realise that breaks the navigation model fairly substantially.

Thank you for taking a look, I appreciate it. Let me know what you think, and we can take it from there.

**Comment by grahammendick** [comment]
Hey, seasons greetings. Thanks, as always, for providing so much detail.

I'm not sure why that behaviour changed in v8.6.0 but it's not a pattern I recommend. You should use React Context to pass values from the parent screen to the modal one; and to call from the modal back up to the parent.

For your example, I've created a `ModalContext`. It holds the `progress` value that the modal displays and the `onSubmit` function so the Modal can call back to the parent.

```jsx
const ModalContext = React.createContext();

const ModalScreen = () => {
  const { progress, onSubmit } = useContext(ProgressContext);
}

const App = () => {
  const [progress, setProgress] = useState(0);
  const onSubmit = () => {}
  return (
    <ModalContext.Provider value={{ progress, onSubmit }}>
       <NavModal>
       </NavModal>
    </ModalContext.Provider>
  );
}
```

**Comment by salockhart** [comment]
Hey @grahammendick, thanks for the quick response. Wasn't expecting to hear from you until the new year!

That makes sense, and using Context for this is a pattern that we have experimented in the past. The extra boilerplate scared us off a bit, but I think I see a way to help with that.

Thanks as always! I will close this out.

**Comment by grahammendick** [comment]
I'm reopening this because I can see the benefit of your approach over using context. It isn't obvious to me why it works on iOS and not Android. I'd like to dig into this and see if it's something the Navigstion router can support. Thanks again for giving me something interesting to chew over with my brussel sprouts

**Comment by grahammendick** [comment]
Hey, the 'Open Modal (children)' works the same for me on iOS and Android. My video shows it working on Android. Note, I removed the 'Open Modal (function prop)' example- it’s invalid because you’re effectively creating a new `Screen` component every render. 

https://user-images.githubusercontent.com/1761227/147478920-6d49f37e-5872-4946-ac5c-6b18a9d0048b.mov

I tried it in v8.7.0 but that shouldn’t matter because I only changed some `BarButton` files in that release. In fact, I think it should work in < v8.6.0 as well. I’m not sure why it doesn’t work on Android for you. Can you give it a retest, please?

So, in summary, the Navigation router supports changing the props of the scene returned from  `renderScene`. Something like

```jsx
const stateNavigator = useMemo(() => {
  const nav = new StateNavigator([{key: 'screen'}]);
  nav.navigate('screen');
  const {screen} = nav.states;
  screen.renderScene = () => <Scene val="A" />;
  return nav;
}, []);

useEffect(() => {
  const {screen} = stateNavigator.states;
  screen.renderScene = () => <Scene val="B" />;
}, [ progress ])
```

If you’re using this approach then be careful because, in your example, you’ve accidentally created a [side-effect in render](https://github.com/grahammendick/navigation/blob/af36d4d43cdf05001524729c757f936235354ab2/NavigationReactNative/sample/singlescreennavigator/App.js#L50). You should only update the `renderScene` inside a `useEffect`. Otherwise you’ll create problems with concurrent rendering in React 18.

**Comment by salockhart** [comment]
Hey, happy new year! Thank you for digging into this.

That's strange that you're seeing the children example work on Android. I've tested on a couple emulators (Pixel 3 API 29, Pixel 4 XL API 28) and a physical device (Samsung Galaxy S8) and I am not seeing it work like you are. I even made some changes to remove the `'Open Modal (function prop)'` example like you had said you did. You're right, that example is not a great one.

Thank you as well for the point about render side-effects, I hadn't thought that part through. I will make sure that I keep an eye out for that.

Regarding your suggested solution, I think that looks good, but I am still having trouble on Android. At this point I'm not sure if it is me or the code. I'm trying to do:

https://github.com/salockhart/navigation/blob/single-screen-navigator/NavigationReactNative/sample/singlescreennavigator/App.js#L68-L94

And I get the same thing: works on iOS and fails to update correctly on Android.

I think the conclusion that I am reaching is that for long term maintainability and principal-of-least-surprise, going the Context route might be better. I can see it work for both iOS and Android, and I think it will make reasoning about this code a little easier in the future.

Here's an example of what I'm trying as a first draft, for something re-usable:

https://github.com/salockhart/navigation/blob/single-screen-navigator/NavigationReactNative/sample/singlescreennavigator/App.js#L102-L124

I'll take my findings back to my team and see what we come up with.

Thanks for your help! Hope you've had a great holiday.

**Comment by grahammendick** [comment]
Happy new year to you, too. I hope you had a good break. My holiday was good. These last few weeks I've been working on improving the Navigation router's support for React Native Web. Is that something you use?

Be careful with your `ModalContext` example because it looks like you’re creating the `WrappedComponent` inside render.
https://github.com/grahammendick/navigation/blob/db0c5e1dfad4c879a5e8acc7adbf961acd01d814/NavigationReactNative/sample/singlescreennavigator/App.js#L103-L107

Instead, you should move the `WrappedComponent` outside and pass the `Component` either in props or Context. Other than that your `ModalContext` example looks good.

Thanks for retesting on a few devices. I'm not sure why we’re not seeing the same behaviour on Android. But I'm not a fan of that approach anyway and I've got a better way to do it that doesn’t require mutating the `renderScene`. In the following code I'm using the `renderScene` prop on the `NavigationStack` and returning the `Wrapper` component. Inside the `Wrapper` component I render the actual scene and pass along the props.

```jsx
const Wrapper = ({state, ...props}) => state.renderScene(props);

const ParentScene = ({progress, onSubmit}) => {
  const modalNavigator = useMemo(() => {
    const navigator = new StateNavigator([{key: 'scene'}])
    const {scene} = stateNavigator.states;
    screen.renderScene = (props) => <Scene {...props} />;
    navigator.navigate('scene');
    return navigator;
  });

  return (
    <NavigationHandler stateNavigator={modalNavigator}>
      <NavigationStack renderScene={(state) => (
        <Wrapper state={state} progress={progress} onSubmit={onSubmit} />
      )} />
    </NavigationHandler>
  );
}
```
I haven't tested this code but it looks sound. Can you give it a run and let me how it goes, please?

**Comment by salockhart** [comment]
> Instead, you should move the WrappedComponent outside and pass the Component either in props or Context. Other than that your ModalContext example looks good.

Good point! I was actually thinking of making an HOC to wire up the component with the context, which should be able to solve the same problem, I think. I'll keep this in mind though, thank you.

> I haven't tested this code but it looks sound. Can you give it a run and let me how it goes, please?

Looks sound to me too:

https://github.com/grahammendick/navigation/blob/0ede03b144e6803e57e16c89a14e524c1ae2b9d6/NavigationReactNative/sample/singlescreennavigator/App.js#L173-L190

But.. no joy on Android again. Works without issue on iOS. I've been testing solely on 8.6.0, but upgrading to 8.7.0 hasn't made any difference like you said. I'll test on 8.7.0 from now on, to be up to date.

BTW I am keeping that branch up to date with all of the options we have discussed.

**Comment by grahammendick** [comment]
Thanks for trying that out and for keeping your branch up to date. The branch really helped and I'm know seeing what you're seeing on Android.

The Navigation router tries really hard to avoid unnecessary renders. The problem is I think it's [trying a bit too hard](https://github.com/grahammendick/navigation/blob/50ca4c96728b5584e0e5b26c58c07f0bfd806ba2/NavigationReactNative/src/Scene.tsx#L39). I'm going to try relaxing the check so it allows the topmost scene of the stack to re-render even if there hasn't been a navigation.

For now, you should stick to the Context approach but I aim to get the `renderScene` example working for all versions of the Navigation router (including < v8.6.0).

**Comment by salockhart** [comment]
Sounds good! Thanks for walking through this with me, if anything I learned a lot about what you consider best practices here.

Let me know if you'd like some eyes to help test any solutions you come up with.

**Comment by grahammendick** [comment]
Hey @salockhart Could you give [my PR](https://github.com/grahammendick/navigation/pull/556) a test, please?   I've tested the `renderScene` prop example but I'd appreciate it if you do your own round of testing, too (even mutating a state's `renderScene` should work).

In the PR I've tried to explain the problem and why we saw the inconsistent results you outlined so clearly.

**Comment by salockhart** [comment]
Hey @grahammendick I've rebased my example branch onto yours, and it looks like everything is working as expected! I'm actually seeing all of the examples working now on both platforms. 

I'll take your recommended approach back to the team once this has been merged.

Thanks for your help on this! I like the behaviour we ended up with.

**Comment by grahammendick** [comment]
>> I like the behaviour we ended up with.

Me too, it's a big improvement. Thanks for raising the issue and working through it with me
