### ISSUE TITLE
react-native-web question

### ISSUE THREAD

**Issue by gezquinndesign** [grahammendick/navigation#595]
Hello, I'm trying to work with the samples in the NavigationReactNativeWeb folder.  I've added an alias (`'navigation-react-native$': 'navigation-react-native-web'`) to the equivalent of my `webpack.config.js` but I'm finding that `Scene` is not exported from the "navigation-react-native-web" package.  It is exported from `navigation-react-native`, should there be an equivalent export  from `navigation-react-native-web`?

**Comment by grahammendick** [comment]
Hey, thanks for getting in touch. I very recently [added a component api to the Navigation router](https://github.com/grahammendick/navigation/pull/592). Even though I haven’t released this work yet I still updated the Twitter sample to use it. Unfortunately that means the Twitter sample isn’t working. Usually there's a small window between me landing a PR and doing a release so there’s no problem updating the Twitter sample with the latest code. But this time is different because I’m a bit distracted with the Fabric migration. So I recommend you use the [zoom sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNativeWeb/sample/zoom) as a setup reference at the moment instead. I hope this isn't too annoying for now.

**Comment by grahammendick** [comment]
Or you could run `git checkout d6420d2747480bf0ecb43adab5ec782eed3e3618` to go back to the latest release and then you can run the Twitter sample from there

**Comment by gezquinndesign** [comment]
Hey, thanks for the clarification and for the great work on this library. That's totally fine, I'll check out the latest release branch and keep an eye out for when it gets published. 👍

**Comment by grahammendick** [comment]
Hey, I've just published the component api so the Twitter samples are working again. Thanks for you patience. I haven't update the docs to use the component api yet

**Comment by grahammendick** [comment]
I've updated the docs to use the component api now. Any reason you reopened this?

**Comment by gezquinndesign** [comment]
Sorry, I opened it and was about to ask another question relating to ReactNativeWeb but worked it out myself.
