### ISSUE TITLE
Scene is not exported from navigation-react-native 8.8.2

### ISSUE THREAD

**Issue by arunmenon1975** [grahammendick/navigation#596]
Hi @grahammendick: 

Its been a while since i've used `navigation-react-native` and i find that there are quite a lot of features and improvements thats been added in since my last usage. 

My current app is tab-based and since i did lose track a bit i though i could start off by using one of the [tab-based samples](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter) . Unfortunately i am getting this typescript error:

`Module '"navigation-react-native"' has no exported member 'Scene'.
`

Im not sure if the example still holds good and probably its because of changes mentioned in #595 or if the `Scene` component has been removed. If it has been removed do i now go back to how it the `tabs` were declared in previous versions ?

**Comment by grahammendick** [comment]
Welcome back! I very recently [added a component api to the Navigation router](https://github.com/grahammendick/navigation/pull/592). Even though I haven’t released this work yet I still updated the Twitter sample to use it. Unfortunately that means the Twitter sample isn’t working. Usually there's a small window between me landing a PR and doing a release so there’s no problem updating the Twitter sample with the latest code. But this time is different because I’m a bit distracted with the Fabric migration. 

But you can run `git checkout d6420d2747480bf0ecb43adab5ec782eed3e3618` to go back to [the latest release](https://github.com/grahammendick/navigation/releases/tag/v6.1.0-Navigation) and then you can run the Twitter sample from there

**Comment by arunmenon1975** [comment]
Ok. Will do that. The component api sounds interesting and from what i see in the the changed Twitter sample, IMO, it does look much more intuitive from a dev perspective as well. Thanks for the response.

**Comment by grahammendick** [comment]
Thanks. I'm gonna update the documentation to use thr new api. The Fabric migration is taking up all my time though

**Comment by grahammendick** [comment]
Hey, I've just published the component api so the Twitter samples are working again. Thanks for you patience. I haven't update the docs to use the component api yet

**Comment by arunmenon1975** [comment]
Just upgraded my in-progress app to the latest version and everything went smooth. 

I half-expected some build issues. The component-api is opt-in so the existing code (without the component api) works just as well. 

Will be gradually porting over to the new api. I like the intuitive approach it has

**Comment by grahammendick** [comment]
Yep, it's fully backward compatible. Glad your upgrade went smoothly 👍

**Comment by grahammendick** [comment]
I've updated the docs to the component api
