### ISSUE TITLE
TabBarItem - fontFamily not respected

### ISSUE THREAD

**Issue by gezquinndesign** [grahammendick/navigation#611]
I've added a custom font to my app.  That font is available and used by other react-native components but not navigation's TabBarItem component.  I'm using the fontFamily prop to set the font, but it does not change.  Repo can be found here: https://github.com/gezquinndesign/rn-monorepo.

**Comment by grahammendick** [comment]
Thanks. It turns out that since iOS 13 the `TabBarItem` font props stopped working. In iOS 13, UIKit changed the way [TabBars are configured](https://emptytheory.com/2019/12/31/using-uitabbarappearance-for-tab-bar-changes-in-ios-13/). Let me know if you want to work on the PR otherwise I'm happy to fix it

**Comment by gezquinndesign** [comment]
Thanks for fixing! 👍
