### ISSUE TITLE
Got error on NavigationStackView.onAfterUpdateTransaction 

### ISSUE THREAD

**Issue by mazipan** [grahammendick/navigation#627]
<img width="1104" alt="Screen Shot 2022-08-04 at 17 24 59" src="https://user-images.githubusercontent.com/7221389/182825178-db4c6a94-45da-457d-9176-76c018347af3.png">

I am not sure how to reproduce this issue, but this is an error from our Crashlytics dashboard.

**Comment by grahammendick** [comment]
Hey, thanks for getting in touch. Don't worry that you can't reproduce it. An error like that is usually an edge case that relies on a very specific sequence and timing. I think the fix is to check the fragment `isAdded` [before the fragments are updated in the NavigationStackView](https://github.com/grahammendick/navigation/blob/ebb230b038d74d1568b8c31ee1ed8eb529905ebb/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/NavigationStackView.java#L92)
```java
if (scenes.size() == 0 || !fragment.isAdded() || fragment.getChildFragmentManager().isStateSaved())
    return;
```
Is this something you can test out and see if the error goes away?

**Comment by mazipan** [comment]
We can reconfirm by check out Crashlytics dashboard, but I am afraid that our current release cycle can not let us check the feedback in short time.

But we can patch the library by our own for instance, using your code above.
Then after we sure that the error gone (which may takes time), we will send you a PR to fix the issue.

How about that?

cc: @galihprakoso

**Comment by grahammendick** [comment]
Thanks @mazipan that sounds great 👍

**Comment by grahammendick** [comment]
Hey @mazipan, how's it going? I'm just checking in to see if you've any feedback yet

**Comment by grahammendick** [comment]
@mazipan could you check, please?

**Comment by grahammendick** [comment]
@mazipan it's cool if it's going to take a while to go through the logs. Just let me know, please 🙏

**Comment by grahammendick** [comment]
@mazipan I'll leave this open for another 2 weeks. If I haven't heard from you before then I'll close it :(

**Comment by galihlprakoso** [comment]
Really really sorry for the late late late response.. 🙏🏻 🥲 I confirmed that the issue is not happening anymore after the patch. Thanks a lot! @grahammendick

**Comment by grahammendick** [comment]
Ah, no problem. Thank you for letting me know. The fix will be in the next release
