### ISSUE TITLE
Scenes, Images, Many More Things Not Working on Web

### ISSUE THREAD

**Issue by nickwebha** [grahammendick/navigation#663]
There is a lot that either does not work or is funky when compiling for React Native Web that does work fine in React Native. I also noticed the [navigation-react-native](https://www.npmjs.com/package/navigation-react-native/) package was updated 10 days ago while the [navigation-react](https://www.npmjs.com/package/navigation-react/) package was last updated 7 months ago. Given the naming of the packages it is also really hard to find search results that are not for similarly named projects.

Is the [navigation-react](https://www.npmjs.com/package/navigation-react/) package dead?

**Comment by grahammendick** [comment]
Hey there, thanks for getting in touch. Have you taken a look at the [twitter sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNativeWeb/sample/twitter)? It's a single code-base that works on iOS, Android and the Web. It uses React Native for iOS and Android and React Native Web for Web. There's no platform checks so the exact same code runs on all three platforms. It includes Scenes, NavigationStack, TabBar, Images, NavigationBar and more.

Please could you be more specific about what you're having trouble with and I'll do my best to help you.

The `navigation-react` package is most definitely not dead. It's alive and well and as fit as a flea. The Navigation router is structured as a core `navigation` package that is library agnostic. Then there are plugin packages that provide library-specific integrations. The `navigation-react` package is the React plugin. It has the React Context implementation for the Navigation router, for example. It's a very thin layer so there isn't much change. The last time it changed was when React 18 came out and I added [support for concurrent rendering](https://github.com/grahammendick/navigation/pull/588) (the new `startTransition` API).

The `navigation-react-native` package is the React Native plugin and it builds on top of the `navigation` and `navigation-react` packages. I update this package more regularly because there's more public API changes in React Native. For example, I've spent the last year updating it to Fabric, the new React Native architecture. 

The Navigation router is 100% native. There isn't a single `View` in the whole library because all components render to their native equivalent. For example, the `TabBar` component renders to a `UITabBarController` on iOS and a `BottomNavigationView` on Android. So I also update the `navigation-react-native` package whenever the underlying native platform changes, too. For example the [`BottomNavigationView` added badges to the tabs](https://github.com/grahammendick/navigation/pull/422).

I hope that helps you, but if you have any more questions please let me know.

**Comment by grahammendick** [comment]
@nickwebha are you happy to close this?

**Comment by nickwebha** [comment]
Sorry, life is happening and I have not been able to get to my computer for almost the last week. Will get back to you.

**Comment by nickwebha** [comment]
Thank you for the detailed response. It really shed light on how everything works.

It has been long enough since I last touched my codebase that I can not remember what issue(s) I was having. When I am able to get back to it and (if) I see something I will fill out a bug report.

Thank you!
