### ISSUE TITLE
Change tabbar border color

### ISSUE THREAD

**Issue by RichardLindhout** [grahammendick/navigation#672]
It would be nice if we could change the tabbar border color, maybe something like this is possible? https://stackoverflow.com/a/32324148/2508481

**Comment by grahammendick** [comment]
Hey! Can you give me more information about what you're trying to do and why, please?

**Comment by RichardLindhout** [comment]
<img width="400" alt="Scherm­afbeelding 2023-02-28 om 21 10 54" src="https://user-images.githubusercontent.com/6492229/221971731-33ed4907-c6b2-4315-859d-4e2e439801ee.png">

I want to change the border color in one of my apps since I have not a white background but slightly green 

<img width="297" alt="Scherm­afbeelding 2023-02-28 om 21 31 07" src="https://user-images.githubusercontent.com/6492229/221971753-636cbdeb-d5c9-473e-8c2d-13a84ab30e4e.png">

**Comment by RichardLindhout** [comment]
I want to have the border a more green tint since gray is off on the greener background

**Comment by grahammendick** [comment]
I tried to set the [shadowColor on the tab bar](https://developer.apple.com/documentation/uikit/uibarappearance/3198008-shadowcolor?language=objc) but couldn't get it working. I'm not keen on the stack overflow you linked to because it looks a bit hacky. If you can find me another way I'll give it a go, otherwise I'm going to close this
