### ISSUE TITLE
custom navigators support

### ISSUE THREAD

**Issue by alidcast** [grahammendick/navigation#696]
hello! i'm pleased to discover this library. looks to be a hidden gem.

I'm scoping out level of compatibility it has with react-navigation.

are custom navigators supported?  Concept borrowed from [react navigation](https://reactnavigation.org/docs/custom-navigators/), but since this library is composed differently, not sure how it applies yet.

also, I noticed the shared transitions and custom animation docs are for Android and Web only; and seems built-into the `NavigationStack`.

Reanimated 3 has [Shared Element Transitions / Layout Animations](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/layout_animations) built in. I wonder if it can be used?

**Comment by grahammendick** [comment]
Hey, it’s great to hear from you. 

The Navigation router is very different to React Navigation. You don’t need any custom navigators because it’s all just components. Instead of custom tab navigators, for example, the Navigation router has a [TabBar component](https://grahammendick.github.io/navigation/documentation/native/tab-bar.html). You use props to configure it as either bottom or top level tabs.

The Navigation router doesn’t have any hand-written UI code. There isn’t a single `View` in the whole library. Every component renders to the native equivalent. Bottom tabs on Android render to the `BottomNavigationView` from the android material library. On iOS they render to `UITabBarController` from UIKit.

There’s no native shared element implementation on iOS. That’s why the Navigation router only supports shared elements on Android. Although I wouldn’t take a dependency on Reanimated, I’d definitely be interested in exposing integration points so someone could hook up Reanimated shared elements to the Navigation router.

I hope that helps. I’m always happy to answer questions

**Comment by grahammendick** [comment]
If you decide to use the Navigation router then I recommend you use its components because they have deep integrations with the native platform that the other 3rd party components you mentioned don't have. For example, on Android there's a `CoordinatorLayout` component that brings collapsing navigation bars with sticky tabs. The Navigation router tries to provide you with the same experience you'd get if you were building native apps without React Native. You lose this if you don't go with the components that come with the Navigation router.

**Comment by grahammendick** [comment]
You could try integrating Reanimated shared elements into the Navigation router

**Comment by grahammendick** [comment]
You could integrate [Hero](https://github.com/HeroTransitions/Hero) into React Native. Looks to be simpler than integrating Reanimated shared elements.

**Comment by POGBAKUTE** [comment]
> You could integrate [Hero](https://github.com/HeroTransitions/Hero) into React Native. Looks to be simpler than integrating Reanimated shared elements.

hello, How can I integrate hero into react native, thanks a lot

**Comment by grahammendick** [comment]
Hi @POGBAKUTE, thanks for getting in touch! The good news is that native shared elements support just landed in iOS 18. Even better news is @gerzonc has [offered to integrate them into the Navigation router](https://github.com/grahammendick/navigation/issues/809). If you’re still interested in integrating Hero though please let me know.

**Comment by grahammendick** [comment]
Hi all, I just [released navigation react native v9.27.0](https://github.com/grahammendick/navigation/releases/tag/v9.27.0-NavigationReactNative) with support for [native shared elements on iOS 18](https://developer.apple.com/documentation/uikit/enhancing-your-app-with-fluid-transitions?language=objc)
