### ISSUE TITLE
expand on concepts in docs

### ISSUE THREAD

**Issue by alidcast** [grahammendick/navigation#698]
third issue! 😄 

I discovered this router because of your commentary on reddit, discussing pains that you resolved. from searching issues, way back you were asking for feedback to improve adoption. I'm not sure where you stand with this project, but one great way of improving adoption is making documentation more welcoming.

it's very cut and dry, with mainly code examples. but concepts/usage aren't explained. nor reasoning for creating library despite existing solutions.

For example, regarding docs, there's a `React` and `React Native` page, former has `navigation-react-mobile` and the latter `navigation-react-native` but it's unclear why so many packages are required and how they're intended to be used. When should one use `NavigationMotion`? Does it work on a mobile device, but not on a native one or a web browser? Outside of looking and code and testing, these usages are unclear.

Would be great to read your explanations for way things work.

Also curious, why did you keep web and native navigators separate? react-navigation has a single API (just disabling animations for stack) so I wonder if you've considered unifying that navigation at all.

**Comment by grahammendick** [comment]
The Navigation router was a web library for React long before it supported React Native.

If you want just want web support then you only need the `navigation` and `navigation-react` packages. The `navigation` package is the core router and it doesn't have any 3rd party dependencies at all. It can be used with your favourite UI library, not just React. The `navigation-react` package has the plumbing to make it work with React. For example, it has Link components and React Context support.

If you want to use native then you'll need both these packages and you'll also need the `navigation-react-native` package. This has the plumbing to make it work with React Native. In particular, it has a `NavigationStack` component that renders to the native stacks on Android (Fragments) and iOS (UINavigationController).

I don't think it's fair that native platforms have stack navigation but the web doesn't. So I created the `navigation-react-mobile` package to bring stack navigation to the web. It's called 'mobile' because you wouldn't want stack navigation on desktop.

The `navigation-react-native-web` package is to the Navigation router as the `react-native-web` package is to React Native. It provides the web equivalent of native components. Under the covers it uses the `NavigationMotion` component from `navigation-react-mobile` to implement the `NavigationStack`.

**Comment by grahammendick** [comment]
No problem, I'm glad it helped. Are you happy to close this?

**Comment by oskarrough** [comment]
>  The navigation package is the core router and it doesn't have any 3rd party dependencies at all. It can be used with your favourite UI library, not just React.

Following up on this, do you have an example or some pointers as to how to use it without React? Have an app with web components and wondering if your router could help finish it.

**Comment by grahammendick** [comment]
Hey! You might find the [unit](https://github.com/grahammendick/navigation/blob/master/Navigation/test/NavigationTest.ts) [tests](https://github.com/grahammendick/navigation/blob/master/Navigation/test/NavigationDataTest.ts) a good place to start?

But here's the rough idea. You create a `StateNavigator` with the scenes in your app

```js
const stateNavigator = new StateNavigator([
  { key: 'hello', route: '' },
  { key: 'world' }
]);
```

Then you can navigate programmatically
```js
stateNavigator.navigate('world', {size: 20});
```
Or with hyperlinks
```js
const link = stateNavigator.navigate('world', {size: 20});
const href = stateNavigator.historyManager.getHref(link);
```

You add a navigation listener to the `stateNavigator` and update the UI
```js
stateNavigator.onNavigate(() => {
  const {state, data} = stateNavigator.stateContext;
  // update UI using the current state and data
});
```
 Another good place to look is the [Navigation React source](https://github.com/grahammendick/navigation/tree/master/NavigationReact/src) because there isn't too much code there and it's an example of connecting these primitives up to rendering library.
