### ISSUE TITLE
Android Studio Build Error

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#757]
Hi,
Am having some challenges building android using android studio. Am not sure if this is related to The Navigation Router. Below is the screenshot. Thanks

![Untitled 2](https://github.com/grahammendick/navigation/assets/6886556/1af095c8-8c08-43a9-9925-0884aa341b19)

**Comment by grahammendick** [comment]
It looks like you're on the latest Navigation router. That means you need to upgrade to React Native 0.73.
React Native isn't backward compatible if you're on Fabric because the new architecture is still in the experimental stage.

I've update [the fabric sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/fabric) to React Native 0.73.
