### ISSUE TITLE
[ios] NavBar color is not set when in it wrapped inside a suspense boundary

### ISSUE THREAD

**Issue by advancedtw** [grahammendick/navigation#837]
I played around with the navbar color not being set consistently and I discovered that if somehow in the view hierarchy at a higher level there is a suspense boundary then it is possible the navbar colors settings (and maybe other values) are not applied when resuming. this behavior is only present on ios.

tested with rn 0.75 and 0.76

example
```tsx
<suspense>
<nav/>
<slowComponent/>
</suspense>
```

It's not really a problem because it's better to have the suspense below the nav so we can show some structure while the content is being loaded but it is important to note that android doesn't behave like that. 

Also I can see at least a use case where the navbar title might be fetched from a remote source.

**Comment by grahammendick** [comment]
Hi, thanks but the Navigation router doesn’t support async `NavigationBar` initialisation.

The Navigation router used to start the transition animation on native before rendering the scene in js. This is bad for lots of reasons but the thing that finally got me to change was that I couldn't get the `UISearchBar` to work on iOS. UIKit doesn't support async `UISearchBar` initialisation. It expects the [UISearchBar to be loaded before the transition starts](https://stackoverflow.com/questions/56392638/ios-search-bar-added-after-a-small-delay-doesn-t-appear-in-the-navigation-bar). So I changed [the Navigation router to render the scene before starting the transition](https://github.com/grahammendick/navigation/pull/245). 

So the Navigation router doesn't support async initialisation because the underlying native platform doesn't support it. I'm sure there are some parts of the `NavigationBar` that do/could work with async initialisation but it's not something the Navigation router tests for or supports.

**Comment by advancedtw** [comment]
> Hi, thanks but the Navigation router doesn’t support async NavigationBar initialisation.
I'm curious I know they are a lot of undocumented behavior is the ios world but if async init is not supported how come it works on android ? maybe you meant no supported in ios ?

**Comment by grahammendick** [comment]
I don't see any advantage supporting it on Android when UIKit doesn't support it. By not supporting it I mean you can't rely on it working not that it doesn't necessarily work. So, even if it works on Android now, I don't test for it and it isn't guaranteed to work in the future.
