### ISSUE TITLE
use with relay

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#85]
Hi,

I just saw your talk at London React Meetup and really want to use it. My application uses relay for data loading. Is it possible to use with relay. An example would be great. 

PS. currently, we use https://github.com/relay-tools/react-router-relay to make them work together.

thanks.
bsr.

**Comment by grahammendick** [comment]
Thanks for getting in touch. It's great to hear you're keen to use the Navigation router.

I haven't used Relay before. But I've skimmed through the documentation and it looks like it will fit together nicely with the Navigation router. You see, the Navigation router doesn't own your components so it plays nicely with other libraries.

To give you an idea of how the Relay/Navigation integration might work, have a look at the following code taken from the Relay docs:

````jsx
window.addEventListener('popstate', () => {
  var userID = getQueryParamFromURI('userID', document.location.href);
  var profileRoute = new ProfileRoute({userID: userID});
  ReactDOM.render(
    <Relay.RootContainer
      Component={UserProfile}
      route={profileRoute}
    />,
    document.getElementById('app')
  );
});
````
You can see that this already looks quite a bit like a router. So, it doesn't need much change to convert this into the equivalent Navigation router code. Instead of listening to URL changes, you put the code inside a `navigated` function and, instead of parsing the query string, you access the `userID` from the data passed in:

````jsx
var states = stateNavigator.states;
states.profile.navigated = (data) => {
  var profileRoute = new ProfileRoute({userID: data.userID});
  ReactDOM.render(
    <Relay.RootContainer
      Component={UserProfile}
      route={profileRoute}
    />,
    document.getElementById('app')
  );
}
````
I'm very keen to include a Relay example in the Navigation router documentation. Thanks for the great idea. I was wondering if you'd like to work on it? I'd be on hand to provide any help you need. If you don't feel like it, that's no problem at all because I'm more than happy to build it. Let me know how you feel.

**Comment by bsr203** [comment]
thanks Graham for the detailed response. So far `react-router` been the default for most of the app I seen, and the recent changes gave an excuse to look for alternative. Joseph Savona, who is the core developer of relay also mentioned his desire for a good routing lib as well.

https://twitter.com/en_JS/status/776507217105129472

I am bit overwhelmed with all the changes and bit occupied at the moment and it won't take too much of your time, please give a try. 

this might be a good one to port as it uses `react-router` and maintained by the author only adapter to use relay + react-router.
https://github.com/taion/relay-todomvc

I too will go through all the docs but it may be a while I get around doing it all.

thanks again for all your effort on this. 

thanks,
bsr.

**Comment by grahammendick** [comment]
Just to let you, I've started work on the Relay example. I can't believe how hard the Relay set up is!

**Comment by bsr203** [comment]
:-) it is indeed an overkill for small application. Using `babel-relay-plugin`, and graphql backend was pretty time consuming for me as well esp with a webpack setup. Also mutations are specified with a complex configuration object.There is a  `v2` already in deployment within FB and heard will be open sourced soon. It addresses some of the awkwardness.
 
I used to use angular1 + rest, but client side caching, handling the change in data shape, .. needed lot of effort especially during initial development. The good think about relay is  that FB has a decent sized team working on it and they use it in production. so hope things get better.

thanks again for your time on this. I loved your presentation especially the part where one can defined the route ONCE and doesn't have to touch the application code for further changes. I have something similar built on top of react-router with a redux store to keep all the config and hope can get rid of all that by using  navigation.

thanks again. bsr.

**Comment by grahammendick** [comment]
When I got to the `babel-relay-plugin` part I nearly fell off my chair ;) Glad to hear it isn't just me that finds it complicated. My example is going to be a read-only master/details app so it won't have any mutations.

With the Navigation router you don't even need to define routes until the end. You can just configure states without routes and then, when your app's working, you add the routes in to tidy up the URLs.

**Comment by bsr203** [comment]
hi. I felt bit guilty as I forgot the effort needed to get the relay part right. I could do an master-detail or CRUD example with react router, and may be you could help to port it to navigation. unless you really want to learn relay :-)

**Comment by grahammendick** [comment]
Thanks, but I've gone too far to turn back now! I think you could've warned me to strap my seatbelt on for the bumpy ride ;)

**Comment by grahammendick** [comment]
I've finished the Relay example (phew!) and would appreciate it if you could review it. Check out the branch called `relayexample` and you'll find the source code in the NavigationReact/sample/relay folder.

All you should need to do to get it running is 

    npm install
    npm run start
	
Then visit http://localhost:8080/.

If you can't get it working then let me know. Can you make sure I haven't done anything too stupid with Relay and tell me what you think of the Navigation router integration, please?

**Comment by bsr203** [comment]
thanks a ton. It works great. It's my son's birthday this weekend, so will get back with you on Monday. thanks again for working on this.

Note:
Readme probably needs to update like

```
npm install
cd NavigationReact/sample/relay
npm install
npm run start
```

**Comment by bsr203** [comment]
one quick remark. There could be a small helper function, so it turns the route configuration of the format 

`    { key: 'people', route: '{pageNumber?}', defaults: { pageNumber: 1 } , component: People, route: peopleRoute },`

to register it with `stateNavigator`. so can avoid doing below for each route

```
stateNavigator.states.people.navigated = (data) => {
    var peopleRoute = new PeopleRoute(data);
    ReactDOM.render(
        <Relay.RootContainer
            renderFetched={data =>
                <People {...data} stateNavigator={stateNavigator} />
            }
            Component={People}
            route={peopleRoute}
            />,
        document.getElementById('content')
    );
}
```

**Comment by grahammendick** [comment]
Happy Birthday to your son. I hope you all have a great day! 

Thanks for your great feedback so far. 

Regarding the Readme, you don't need run `npm install` at the top level to get the Relay example working. So maybe I should just add `cd NavigationReact/sample/relay`?

I like your idea about making a generic way of rendering the Relay RootContainer. I've checked in some code that does this by registering a single navigation handler (instead of one for each state);
````jsx
stateNavigator.onNavigate((oldState, state, data) => {
    var route = state.relayRoute(data);
    var Component = state.component;
    ReactDOM.render(
        <Relay.RootContainer
            renderFetched={data =>
                <Component {...data} stateNavigator={stateNavigator} />
            }
            Component={Component}
            route={route}
            />,
        document.getElementById('content')
    );
});
````
And the corresponding StateNavigator looks like this:
````js
var stateNavigator = new StateNavigator([
    { key: 'people', route: '{pageNumber?}', defaults: { pageNumber: 1 },
        component: People, relayRoute: (data) => new PeopleRoute(data) },
    { key: 'person', route: 'person/{id}', defaults: { id: 0 }, trackCrumbTrail: true,
        component: Person, relayRoute: (data) => new PersonRoute(data) }
]);
````

**Comment by bsr203** [comment]
Thank you for the wishes.

I went through the docs, and some of the blog posts and really excited about how simple is to use compared to `react-router`.  I may start with migration in coming weeks.

meanwhile, is there a way to to nest the route configuration. With `react-router`, I was using https://github.com/ReactTraining/react-router/blob/master/docs/API.md#childroutes. 

About the code, I like it as it is simple to demonstrate the router. But, typical, idiomatic usage of relay involve

1. https://github.com/graphql/graphql-relay-js to constuct a globally unique id and connection support, which is specified at https://facebook.github.io/relay/docs/graphql-relay-specification.html

2. viewer type  (https://github.com/relayjs/relay-examples/blob/master/todo/data/database.js)

3. No `PeopleType`, but query `people` returns a List of Person

4. on the client side reuse queries through fragments

```
fragments: {
  viewer: () => Relay.QL`
    fragment on Viewer {
      people(first: 10) {
        edges {
          cursor
          node {
            ${Person.getFragment('viewer')}
          }
        }
      }
    }
  `,
```
not sure we need to spend time on it now, as the example clearly shows how to use the router client side. If I found the example is inadequate to use with relay while I am migrating my code, I can make the modifications.

please comment on nested route.

Thanks again for your time.
bsr.

**Comment by grahammendick** [comment]
Thanks for going through the code and for providing such great feedback. Much appreciated.

The Navigation router doesn't do nested configuration. You might think you need it if you've come from the react router, but it's the UI that needs to be nested not the configuration. Take the relay master/details example and, instead of showing the person on a different page, let's show the person below the people list when selected. 

Remember that the Navigation router is the data-first router. So, we don't worry about the URLs until the end. Instead we build our UI based on data/props. We put logic into the People component that decides whether to show the Person component based on the id prop passed in.

Once we've got our nested UI working we can make our URLs look however we want without changing any code. Setting the route to 'people/{id?}', for example, produces URLs of '/people' and '/people/10'. Setting the route to 'people+/person/{id}' produces URLs of '/people' and '/people/person/10'. Here's a [JsFiddle of the example](https://jsfiddle.net/s7entpb7/) to show what I mean.

Thanks for your four points on Relay usage. I knew I wasn't doing it right. I tried getting rid of the PeopleType but got in a right pickle! I also tried writing a fragment to get at the individual person through the PeopleQuery but couldn't get my head around it. If I merge my relay example into main, could you send me a PR with the Relay fixed, please?

**Comment by bsr203** [comment]
Indeed, I was not really using nested routed the way `react-router` propose, but mainly to not repeat the url fragments. that is nesting `person` under `people` make the url `people/person`. So mainly was looking for a way not to repeat strings in case I need to change keys. But, I may achieve the same through a function to construct the route so can easily refactor if I need to.

I definitely would help on relay part, but please give time till I get to use the library in few weeks.

I would also try to get feedback from some of the key members of react/relay community so navigation` get mentioned as a good solution for wider routing problems.

thank you.
bsr.

**Comment by grahammendick** [comment]
There's no rush, whenever you get the time. If you have any questions please let me know. I'm always happy to help. Are you happy for me to merge the relay example into main?

Thanks very much for offering to promote the Navigaton router.

**Comment by bsr203** [comment]
I think you can merge :-) as it shows how to use with relay route and works great. We will cleanup the backend later. thanks again for your effort on this.
