### ISSUE TITLE
npm & docs

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#87]
Hi,

 it would be nice to have the npm package info in this page http://grahammendick.github.io/navigation/download/index.html also in the github readme. 

It would be also great to have an API section in the docs which lists all available options and API.

**Comment by grahammendick** [comment]
Thanks for the great suggestions. Adding the npm download information to the readme makes a lot of sense, so I'll add that shortly.

I'm less convinced about including the Api in the docs. Not because it's not a great idea but, until the Navigation router takes off, I'm not sure an Api guide works that well. You see, I want the docs to be super-friendly to new users and think an Api Guide can be confusing and detract from the existing docs. There is a [Definitely Typed file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/navigation/navigation.d.ts) which you can use for the time being. Let me know what you think because I'm happy to be persuaded otherwise.

**Comment by bsr203** [comment]
thanks. may be a link to the typescript def file in the doc & readme would be quite sufficient. thanks again for quick response.

**Comment by grahammendick** [comment]
What about if I link to the Typescript Def from the download page? That way I'll include it on the readme when I add the Download section you suggested.

**Comment by bsr203** [comment]
sure.. thanks.

**Comment by bsr203** [comment]
btw, I am trying `navigation` now in my code to replace `react-router`, keep you posted. hope u'll be around today :-)

**Comment by grahammendick** [comment]
Great to hear! I'm around for the next few hours and popping out this evening (UK time). Please ask any questions and I'll get back to you as soon as I can.

**Comment by bsr203** [comment]
converting one route went quite smooth, and need more effort on changing all the links and routes. but so happy to reduce the few dependencies and getting back control :-) will update you.

**Comment by grahammendick** [comment]
Glad you're doing well! I've linked to the TypeScript declaration from the [download page](http://grahammendick.github.io/navigation/download/index.html) and added the npm packages to the [readme](https://github.com/grahammendick/navigation#download). When you've got a moment can you check you're happy. Thanks.

**Comment by bsr203** [comment]
well.. I am not sure this repo is only intended for react usage as I see angular, inferno, and packages for integration with other web frameworks. If, `navigation` supports all, I may say, import `navigation`for router , and list the frameworks supported and the additional package for each of them. Hope I am not taking up too much of your time.

**Comment by grahammendick** [comment]
Don't worry about taking up my time, I'm happy you're up for a chat. I've decided against marketing the Navigation router as being library-agnostic for now. Mainly because it's less successful with other frameworks like angular and knockout where the router has to load the views. I don't want to get into the view-loading business but I'm hoping that, when the Navigation router takes off, people will write angular and knockout plugins that do the view loading. Or, perhaps other frameworks will realise the beauty of React and provide an Api like `ReactDOM.render` so that developers can load their own views.

**Comment by bsr203** [comment]
ok.. I think the doc is fine for now. thanks.
