### ISSUE TITLE
Qn: Breadcrumb Trail

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#92]
I read the section http://grahammendick.github.io/navigation/documentation/breadcrumb-trail.html

as I understood, this provides more of a navigation back functionality through selected states within history. Not sure this is same as [breadcrumb navigation](https://en.wikipedia.org/wiki/Breadcrumb_(navigation)). Say user is provided a direct link to `/author/xyz/book/123`, and if I have Breadcrumb trail ( static link) to `/author/{id}`, does it populate correctly? I don't see the relevance of distance there, unless a way to specify hierarchy.

I could build my trail with `NavigationLink`, but want to make sure.

thanks,
bsr

**Comment by grahammendick** [comment]
There are a couple of definitions of a breadcrumb trail. I've gone with the following (taken from your wikipedia link)

> A breadcrumb trail tracks and displays each page viewed by a visitor of a website...in the order the pages were viewed

This doesn't fit your purposes because it sounds like you want the other definition:

> a hierarchy of the current page in relation to the website's structure

So, yes, you will have to buid your own.

You might find it easier to use the` RefreshLink` than the `NavigationLink` for the author/book example. A `RefreshLink` is a `NavigationLink` that navigates to the current `State` so if you configure your example with one State:
```js
var stateNavigator = new StateNavigator([
  {key: 'author', route: 'author/{id}+/book/{title}'}
]);
```
then you can build a Hyperlink to the author when viewing a book like this:
```jsx
<RefreshLink
  navigationData={book: ''}
  includeCurrentData={true}>
  Author
</RefreshLink>
```

Setting `includeCurrentData` means it will keep the current author id. And clearing the book id means it'll generate the href `/author/xyz`.

**Comment by grahammendick** [comment]
I should just stay that `includeCurrentData` also works with `NavigationLinks`. So if author and book are different `States`, you can build a breadcrumb from book to author like this:

```jsx
<NavigationLink
  stateKey="author"
  navigationData={book: ''}
  includeCurrentData={true}>
  Author
</NavigationLink>
```

**Comment by bsr203** [comment]
thanks a ton. I think the second example with `NavigationLink` sounds more apt for me. I didn't notice `includeCurrentData`, and thanks for pointing it out. I ported almost everything from `react-router` except navigating from actionCreators through redux actions. I may move those navigation back to the components. thanks again for your help.

**Comment by grahammendick** [comment]
No problem. Thanks for asking interesting questions. You might like my blog about how to use [includeCurrentData to streamline your components](https://navigation4asp.net/2016/06/05/streamlined-react-components/).
